/**
 * Vocatopia — 教育部國中英語2000字批次匯入腳本
 *
 * 用法：
 *   node supabase/import_words.js           # 全部匯入（跳過已存在）
 *   node supabase/import_words.js --dry-run # 只顯示統計，不寫入
 *   node supabase/import_words.js --reset   # 清除 cache 重新生成
 *
 * 流程：
 *   1. 從 DB 取得已存在的單字
 *   2. 比對 WORD_LIST，找出缺少的單字
 *   3. 用 Gemini 每批 25 個生成 phonetic / definition / example
 *   4. 儲存進度到 words_cache.json（可中斷後繼續）
 *   5. 批次 upsert 到 Supabase
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });

const { GoogleGenerativeAI } = require('@google/generative-ai');
const { createClient }        = require('@supabase/supabase-js');
const fs   = require('fs');
const path = require('path');

const supabase   = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SECRET_KEY);
const genAI      = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const CACHE_FILE = path.join(__dirname, 'words_cache.json');
const BATCH_SIZE = 50;       // gemini-1.5-flash 支援更大輸出，每批可處理更多
const BATCH_DELAY_MS = 5000; // 1.5-flash RPM=15，每批間隔 5 秒

const DRY_RUN = process.argv.includes('--dry-run');
const RESET   = process.argv.includes('--reset');

// ══════════════════════════════════════════════════════════════════
// 教育部國中英語2000字清單
// 格式：[word, pos繁中, level]  level: 1=基礎, 2=進階
// ══════════════════════════════════════════════════════════════════
const WORD_LIST = [
  // ── Level 1 高頻基礎 ────────────────────────────────────────
  ['able','形容詞',1],['absence','名詞',1],['accept','動詞',1],['accident','名詞',1],
  ['achieve','動詞',1],['action','名詞',1],['actually','副詞',1],['adult','名詞',1],
  ['advice','名詞',1],['afford','動詞',1],['afraid','形容詞',1],['after','介系詞',1],
  ['afternoon','名詞',1],['again','副詞',1],['age','名詞',1],['ago','副詞',1],
  ['agree','動詞',1],['ahead','副詞',1],['air','名詞',1],['album','名詞',1],
  ['allow','動詞',1],['almost','副詞',1],['alone','形容詞',1],['already','副詞',1],
  ['also','副詞',1],['always','副詞',1],['amount','名詞',1],['angry','形容詞',1],
  ['animal','名詞',1],['another','形容詞',1],['answer','動詞',1],['anyone','代名詞',1],
  ['anything','代名詞',1],['anywhere','副詞',1],['appear','動詞',1],['area','名詞',1],
  ['around','介系詞',1],['arrive','動詞',1],['art','名詞',1],['ask','動詞',1],
  ['attention','名詞',1],['attitude','名詞',1],['aunt','名詞',1],['avoid','動詞',1],
  ['award','名詞',1],['away','副詞',1],['baby','名詞',1],['back','副詞',1],
  ['bad','形容詞',1],['bag','名詞',1],['bank','名詞',1],['base','名詞',1],
  ['bath','名詞',1],['be','動詞',1],['beach','名詞',1],['beautiful','形容詞',1],
  ['because','連接詞',1],['become','動詞',1],['before','介系詞',1],['begin','動詞',1],
  ['believe','動詞',1],['belong','動詞',1],['benefit','名詞',1],['beside','介系詞',1],
  ['best','形容詞',1],['better','形容詞',1],['between','介系詞',1],['big','形容詞',1],
  ['bird','名詞',1],['birthday','名詞',1],['body','名詞',1],['book','名詞',1],
  ['boring','形容詞',1],['bother','動詞',1],['box','名詞',1],['brave','形容詞',1],
  ['bread','名詞',1],['break','動詞',1],['breath','名詞',1],['bridge','名詞',1],
  ['bright','形容詞',1],['bring','動詞',1],['brother','名詞',1],['build','動詞',1],
  ['busy','形容詞',1],['buy','動詞',1],['by','介系詞',1],['call','動詞',1],
  ['calm','形容詞',1],['can','助動詞',1],['care','動詞',1],['careful','形容詞',1],
  ['carry','動詞',1],['catch','動詞',1],['cause','名詞',1],['certain','形容詞',1],
  ['chance','名詞',1],['change','動詞',1],['character','名詞',1],['check','動詞',1],
  ['child','名詞',1],['choice','名詞',1],['choose','動詞',1],['city','名詞',1],
  ['class','名詞',1],['clean','形容詞',1],['clear','形容詞',1],['climb','動詞',1],
  ['close','動詞',1],['clothes','名詞',1],['cloud','名詞',1],['cold','形容詞',1],
  ['collect','動詞',1],['color','名詞',1],['come','動詞',1],['comfortable','形容詞',1],
  ['communicate','動詞',1],['compare','動詞',1],['complete','動詞',1],['condition','名詞',1],
  ['confident','形容詞',1],['connect','動詞',1],['consider','動詞',1],['continue','動詞',1],
  ['control','動詞',1],['cook','動詞',1],['cool','形容詞',1],['copy','動詞',1],
  ['correct','形容詞',1],['cost','名詞',1],['country','名詞',1],['cousin','名詞',1],
  ['cover','動詞',1],['create','動詞',1],['cry','動詞',1],['culture','名詞',1],
  ['cup','名詞',1],['cut','動詞',1],['dance','動詞',1],['dark','形容詞',1],
  ['day','名詞',1],['dear','形容詞',1],['decide','動詞',1],['deep','形容詞',1],
  ['describe','動詞',1],['develop','動詞',1],['different','形容詞',1],['difficult','形容詞',1],
  ['dinner','名詞',1],['dirty','形容詞',1],['discover','動詞',1],['discuss','動詞',1],
  ['disease','名詞',1],['do','動詞',1],['door','名詞',1],['down','副詞',1],
  ['draw','動詞',1],['dream','名詞',1],['drink','動詞',1],['drive','動詞',1],
  ['drop','動詞',1],['during','介系詞',1],['each','形容詞',1],['early','副詞',1],
  ['earth','名詞',1],['easy','形容詞',1],['eat','動詞',1],['education','名詞',1],
  ['effect','名詞',1],['else','副詞',1],['energy','名詞',1],['enjoy','動詞',1],
  ['enough','形容詞',1],['enter','動詞',1],['environment','名詞',1],['especially','副詞',1],
  ['even','副詞',1],['evening','名詞',1],['ever','副詞',1],['every','形容詞',1],
  ['everyone','代名詞',1],['everything','代名詞',1],['example','名詞',1],['excellent','形容詞',1],
  ['excited','形容詞',1],['experience','名詞',1],['explain','動詞',1],['face','名詞',1],
  ['fail','動詞',1],['fall','動詞',1],['family','名詞',1],['famous','形容詞',1],
  ['far','副詞',1],['fast','副詞',1],['favorite','形容詞',1],['feel','動詞',1],
  ['few','形容詞',1],['field','名詞',1],['finally','副詞',1],['find','動詞',1],
  ['finish','動詞',1],['fire','名詞',1],['fish','名詞',1],['floor','名詞',1],
  ['flower','名詞',1],['fly','動詞',1],['focus','動詞',1],['follow','動詞',1],
  ['food','名詞',1],['foreign','形容詞',1],['forget','動詞',1],['forward','副詞',1],
  ['free','形容詞',1],['freedom','名詞',1],['fresh','形容詞',1],['friend','名詞',1],
  ['friendly','形容詞',1],['from','介系詞',1],['full','形容詞',1],['fun','名詞',1],
  ['future','名詞',1],['game','名詞',1],['garden','名詞',1],['get','動詞',1],
  ['gift','名詞',1],['give','動詞',1],['glad','形容詞',1],['goal','名詞',1],
  ['good','形容詞',1],['government','名詞',1],['grade','名詞',1],['grateful','形容詞',1],
  ['great','形容詞',1],['group','名詞',1],['grow','動詞',1],['guess','動詞',1],
  ['gym','名詞',1],['habit','名詞',1],['happen','動詞',1],['happy','形容詞',1],
  ['hard','形容詞',1],['have','動詞',1],['health','名詞',1],['hear','動詞',1],
  ['heart','名詞',1],['help','動詞',1],['helpful','形容詞',1],['here','副詞',1],
  ['history','名詞',1],['hobby','名詞',1],['hold','動詞',1],['holiday','名詞',1],
  ['home','名詞',1],['homework','名詞',1],['honest','形容詞',1],['hope','動詞',1],
  ['hotel','名詞',1],['house','名詞',1],['however','副詞',1],['hungry','形容詞',1],
  ['hurt','動詞',1],['idea','名詞',1],['imagine','動詞',1],['important','形容詞',1],
  ['improve','動詞',1],['include','動詞',1],['influence','名詞',1],['interest','名詞',1],
  ['interested','形容詞',1],['introduce','動詞',1],['invite','動詞',1],['island','名詞',1],
  ['join','動詞',1],['journey','名詞',1],['jump','動詞',1],['just','副詞',1],
  ['keep','動詞',1],['kind','形容詞',1],['know','動詞',1],['language','名詞',1],
  ['last','形容詞',1],['late','副詞',1],['laugh','動詞',1],['learn','動詞',1],
  ['leave','動詞',1],['letter','名詞',1],['life','名詞',1],['like','動詞',1],
  ['listen','動詞',1],['live','動詞',1],['long','形容詞',1],['look','動詞',1],
  ['love','動詞',1],['lucky','形容詞',1],['lunch','名詞',1],['make','動詞',1],
  ['many','形容詞',1],['market','名詞',1],['maybe','副詞',1],['mean','動詞',1],
  ['meet','動詞',1],['message','名詞',1],['mind','名詞',1],['miss','動詞',1],
  ['moment','名詞',1],['money','名詞',1],['month','名詞',1],['more','副詞',1],
  ['morning','名詞',1],['most','副詞',1],['move','動詞',1],['much','副詞',1],
  ['music','名詞',1],['must','助動詞',1],['nature','名詞',1],['need','動詞',1],
  ['never','副詞',1],['next','形容詞',1],['nice','形容詞',1],['night','名詞',1],
  ['noise','名詞',1],['now','副詞',1],['number','名詞',1],['often','副詞',1],
  ['old','形容詞',1],['only','副詞',1],['open','動詞',1],['order','名詞',1],
  ['other','形容詞',1],['outside','副詞',1],['own','形容詞',1],['page','名詞',1],
  ['parent','名詞',1],['park','名詞',1],['part','名詞',1],['pass','動詞',1],
  ['pay','動詞',1],['people','名詞',1],['phone','名詞',1],['photo','名詞',1],
  ['pick','動詞',1],['picture','名詞',1],['place','名詞',1],['plan','名詞',1],
  ['play','動詞',1],['please','動詞',1],['popular','形容詞',1],['possible','形容詞',1],
  ['practice','動詞',1],['prepare','動詞',1],['pretty','形容詞',1],['price','名詞',1],
  ['problem','名詞',1],['proud','形容詞',1],['put','動詞',1],['question','名詞',1],
  ['quick','形容詞',1],['quiet','形容詞',1],['rain','名詞',1],['read','動詞',1],
  ['ready','形容詞',1],['real','形容詞',1],['reason','名詞',1],['receive','動詞',1],
  ['remember','動詞',1],['repeat','動詞',1],['rest','名詞',1],['return','動詞',1],
  ['ride','動詞',1],['right','形容詞',1],['room','名詞',1],['run','動詞',1],
  ['safe','形容詞',1],['same','形容詞',1],['save','動詞',1],['say','動詞',1],
  ['school','名詞',1],['season','名詞',1],['second','形容詞',1],['see','動詞',1],
  ['seem','動詞',1],['send','動詞',1],['share','動詞',1],['show','動詞',1],
  ['sick','形容詞',1],['simple','形容詞',1],['sing','動詞',1],['sister','名詞',1],
  ['sit','動詞',1],['skill','名詞',1],['sleep','動詞',1],['slow','形容詞',1],
  ['small','形容詞',1],['smile','動詞',1],['someone','代名詞',1],['something','代名詞',1],
  ['sometimes','副詞',1],['soon','副詞',1],['sorry','形容詞',1],['speak','動詞',1],
  ['spend','動詞',1],['sport','名詞',1],['start','動詞',1],['stay','動詞',1],
  ['still','副詞',1],['stop','動詞',1],['store','名詞',1],['story','名詞',1],
  ['street','名詞',1],['strong','形容詞',1],['student','名詞',1],['study','動詞',1],
  ['subject','名詞',1],['sugar','名詞',1],['summer','名詞',1],['surprise','名詞',1],
  ['swim','動詞',1],['table','名詞',1],['take','動詞',1],['talk','動詞',1],
  ['tall','形容詞',1],['teacher','名詞',1],['team','名詞',1],['tell','動詞',1],
  ['thank','動詞',1],['then','副詞',1],['think','動詞',1],['though','連接詞',1],
  ['through','介系詞',1],['time','名詞',1],['tired','形容詞',1],['today','副詞',1],
  ['together','副詞',1],['tomorrow','副詞',1],['tonight','副詞',1],['too','副詞',1],
  ['town','名詞',1],['train','名詞',1],['travel','動詞',1],['tree','名詞',1],
  ['true','形容詞',1],['try','動詞',1],['turn','動詞',1],['uncle','名詞',1],
  ['understand','動詞',1],['until','連接詞',1],['use','動詞',1],['usually','副詞',1],
  ['very','副詞',1],['visit','動詞',1],['voice','名詞',1],['wait','動詞',1],
  ['walk','動詞',1],['want','動詞',1],['warm','形容詞',1],['watch','動詞',1],
  ['way','名詞',1],['wear','動詞',1],['weather','名詞',1],['week','名詞',1],
  ['well','副詞',1],['when','副詞',1],['where','副詞',1],['while','連接詞',1],
  ['wide','形容詞',1],['will','助動詞',1],['win','動詞',1],['wish','動詞',1],
  ['wonderful','形容詞',1],['word','名詞',1],['work','動詞',1],['world','名詞',1],
  ['worry','動詞',1],['write','動詞',1],['wrong','形容詞',1],['year','名詞',1],
  ['yesterday','副詞',1],['yet','副詞',1],['young','形容詞',1],

  // ── Level 2 進階 ────────────────────────────────────────────
  ['ability','名詞',2],['above','介系詞',2],['abroad','副詞',2],['according','副詞',2],
  ['accurate','形容詞',2],['active','形容詞',2],['activity','名詞',2],['actually','副詞',2],
  ['add','動詞',2],['address','名詞',2],['adventure','名詞',2],['affect','動詞',2],
  ['afford','動詞',2],['against','介系詞',2],['agent','名詞',2],['aim','動詞',2],
  ['alive','形容詞',2],['announce','動詞',2],['apart','副詞',2],['apologize','動詞',2],
  ['apply','動詞',2],['appreciate','動詞',2],['approach','動詞',2],['appropriate','形容詞',2],
  ['argue','動詞',2],['arrange','動詞',2],['arrest','動詞',2],['article','名詞',2],
  ['attack','動詞',2],['attempt','動詞',2],['attract','動詞',2],['audience','名詞',2],
  ['author','名詞',2],['available','形容詞',2],['background','名詞',2],['balance','名詞',2],
  ['barely','副詞',2],['behavior','名詞',2],['beyond','介系詞',2],['board','名詞',2],
  ['border','名詞',2],['brain','名詞',2],['branch','名詞',2],['breath','名詞',2],
  ['bully','動詞',2],['button','名詞',2],['calendar','名詞',2],['campaign','名詞',2],
  ['campus','名詞',2],['capable','形容詞',2],['capital','名詞',2],['captain','名詞',2],
  ['career','名詞',2],['celebrate','動詞',2],['challenge','名詞',2],['champion','名詞',2],
  ['charity','名詞',2],['chemical','名詞',2],['citizen','名詞',2],['claim','動詞',2],
  ['climate','名詞',2],['coach','名詞',2],['collect','動詞',2],['college','名詞',2],
  ['combine','動詞',2],['comfortable','形容詞',2],['command','動詞',2],['community','名詞',2],
  ['competition','名詞',2],['complain','動詞',2],['complex','形容詞',2],['concentrate','動詞',2],
  ['concert','名詞',2],['confuse','動詞',2],['congress','名詞',2],['contact','動詞',2],
  ['contain','動詞',2],['contest','名詞',2],['convenient','形容詞',2],['conversation','名詞',2],
  ['cooperate','動詞',2],['courage','名詞',2],['creature','名詞',2],['crime','名詞',2],
  ['crowd','名詞',2],['curious','形容詞',2],['customer','名詞',2],['damage','動詞',2],
  ['danger','名詞',2],['deadline','名詞',2],['deaf','形容詞',2],['deal','動詞',2],
  ['degree','名詞',2],['delay','動詞',2],['deliver','動詞',2],['design','動詞',2],
  ['destroy','動詞',2],['detective','名詞',2],['diet','名詞',2],['digital','形容詞',2],
  ['disappear','動詞',2],['disappoint','動詞',2],['distance','名詞',2],['divide','動詞',2],
  ['double','形容詞',2],['doubt','名詞',2],['downtown','名詞',2],['effort','名詞',2],
  ['electronic','形容詞',2],['emotion','名詞',2],['encourage','動詞',2],['enemy','名詞',2],
  ['engine','名詞',2],['enormous','形容詞',2],['equality','名詞',2],['escape','動詞',2],
  ['event','名詞',2],['evidence','名詞',2],['exact','形容詞',2],['exchange','動詞',2],
  ['exercise','名詞',2],['exist','動詞',2],['expect','動詞',2],['expense','名詞',2],
  ['explore','動詞',2],['export','動詞',2],['express','動詞',2],['extra','形容詞',2],
  ['extreme','形容詞',2],['factor','名詞',2],['fair','形容詞',2],['familiar','形容詞',2],
  ['fantastic','形容詞',2],['fear','名詞',2],['female','形容詞',2],['festival','名詞',2],
  ['figure','名詞',2],['film','名詞',2],['fit','形容詞',2],['fix','動詞',2],
  ['force','名詞',2],['formal','形容詞',2],['fortune','名詞',2],['found','動詞',2],
  ['function','名詞',2],['funeral','名詞',2],['global','形容詞',2],['gradually','副詞',2],
  ['grand','形容詞',2],['guard','動詞',2],['guide','動詞',2],['handle','動詞',2],
  ['harm','動詞',2],['headline','名詞',2],['heal','動詞',2],['hero','名詞',2],
  ['hire','動詞',2],['honor','名詞',2],['huge','形容詞',2],['humble','形容詞',2],
  ['humor','名詞',2],['hunger','名詞',2],['identity','名詞',2],['ignore','動詞',2],
  ['illegal','形容詞',2],['image','名詞',2],['import','動詞',2],['increase','動詞',2],
  ['independence','名詞',2],['industry','名詞',2],['inform','動詞',2],['injure','動詞',2],
  ['innocent','形容詞',2],['internet','名詞',2],['invent','動詞',2],['investigate','動詞',2],
  ['isolate','動詞',2],['issue','名詞',2],['judge','動詞',2],['junior','形容詞',2],
  ['lack','動詞',2],['law','名詞',2],['leader','名詞',2],['leisure','名詞',2],
  ['limited','形容詞',2],['location','名詞',2],['lonely','形容詞',2],['loud','形容詞',2],
  ['lovely','形容詞',2],['loyal','形容詞',2],['main','形容詞',2],['manage','動詞',2],
  ['manner','名詞',2],['material','名詞',2],['media','名詞',2],['mental','形容詞',2],
  ['mention','動詞',2],['mistake','名詞',2],['modern','形容詞',2],['moral','形容詞',2],
  ['mountain','名詞',2],['natural','形容詞',2],['necessary','形容詞',2],['negative','形容詞',2],
  ['neighbor','名詞',2],['nervous','形容詞',2],['noble','形容詞',2],['normal','形容詞',2],
  ['notice','動詞',2],['novel','名詞',2],['obey','動詞',2],['ocean','名詞',2],
  ['office','名詞',2],['opinion','名詞',2],['opportunity','名詞',2],['organize','動詞',2],
  ['original','形容詞',2],['overcome','動詞',2],['painful','形容詞',2],['particular','形容詞',2],
  ['partner','名詞',2],['patient','形容詞',2],['perform','動詞',2],['period','名詞',2],
  ['personal','形容詞',2],['physical','形容詞',2],['planet','名詞',2],['plant','名詞',2],
  ['poem','名詞',2],['polite','形容詞',2],['pollute','動詞',2],['positive','形容詞',2],
  ['powerful','形容詞',2],['present','動詞',2],['pressure','名詞',2],['prevent','動詞',2],
  ['process','名詞',2],['produce','動詞',2],['profit','名詞',2],['program','名詞',2],
  ['project','名詞',2],['promise','動詞',2],['protect','動詞',2],['prove','動詞',2],
  ['provide','動詞',2],['publish','動詞',2],['punish','動詞',2],['quality','名詞',2],
  ['raise','動詞',2],['reach','動詞',2],['realize','動詞',2],['recent','形容詞',2],
  ['recycle','動詞',2],['reduce','動詞',2],['reflect','動詞',2],['relationship','名詞',2],
  ['relax','動詞',2],['remain','動詞',2],['repair','動詞',2],['replace','動詞',2],
  ['report','動詞',2],['research','名詞',2],['resource','名詞',2],['respect','動詞',2],
  ['respond','動詞',2],['result','名詞',2],['review','動詞',2],['reward','名詞',2],
  ['risk','名詞',2],['role','名詞',2],['rule','名詞',2],['schedule','名詞',2],
  ['science','名詞',2],['search','動詞',2],['series','名詞',2],['serious','形容詞',2],
  ['settle','動詞',2],['several','形容詞',2],['shelter','名詞',2],['situation','名詞',2],
  ['social','形容詞',2],['society','名詞',2],['solution','名詞',2],['solve','動詞',2],
  ['special','形容詞',2],['speech','名詞',2],['spirit','名詞',2],['spread','動詞',2],
  ['stage','名詞',2],['standard','名詞',2],['success','名詞',2],['suffer','動詞',2],
  ['support','動詞',2],['survive','動詞',2],['symbol','名詞',2],['system','名詞',2],
  ['talent','名詞',2],['technology','名詞',2],['terrible','形容詞',2],['therefore','副詞',2],
  ['title','名詞',2],['tradition','名詞',2],['train','動詞',2],['trust','動詞',2],
  ['truth','名詞',2],['typical','形容詞',2],['unless','連接詞',2],['unusual','形容詞',2],
  ['update','動詞',2],['upon','介系詞',2],['value','名詞',2],['variety','名詞',2],
  ['various','形容詞',2],['view','名詞',2],['village','名詞',2],['violent','形容詞',2],
  ['volunteer','名詞',2],['vote','動詞',2],['waste','動詞',2],['wealth','名詞',2],
  ['weight','名詞',2],['whether','連接詞',2],['wild','形容詞',2],['willing','形容詞',2],
  ['wisdom','名詞',2],['within','介系詞',2],['without','介系詞',2],['worth','形容詞',2],
  ['accident','名詞',2],['achieve','動詞',2],['affect','動詞',2],['agree','動詞',2],
  ['announcement','名詞',2],['apartment','名詞',2],['argument','名詞',2],['assignment','名詞',2],
  ['athlete','名詞',2],['atmosphere','名詞',2],['automatically','副詞',2],['battery','名詞',2],
  ['bicycle','名詞',2],['billion','數詞',2],['blank','形容詞',2],['blossom','名詞',2],
  ['bookstore','名詞',2],['broadcast','動詞',2],['budget','名詞',2],['button','名詞',2],
  ['cafeteria','名詞',2],['calculator','名詞',2],['calm','動詞',2],['cancel','動詞',2],
  ['careless','形容詞',2],['castle','名詞',2],['category','名詞',2],['cause','動詞',2],
  ['ceiling','名詞',2],['century','名詞',2],['ceremony','名詞',2],['chapter','名詞',2],
  ['charity','名詞',2],['chart','名詞',2],['chef','名詞',2],['chemical','形容詞',2],
  ['childhood','名詞',2],['clap','動詞',2],['classroom','名詞',2],['clerk','名詞',2],
  ['clever','形容詞',2],['click','動詞',2],['comfortable','形容詞',2],['commute','動詞',2],
  ['complaint','名詞',2],['concentrate','動詞',2],['conclusion','名詞',2],['confident','形容詞',2],
  ['congratulate','動詞',2],['connect','動詞',2],['construction','名詞',2],['continue','動詞',2],
  ['convenience','名詞',2],['cope','動詞',2],['countryside','名詞',2],['coupon','名詞',2],
  ['creative','形容詞',2],['crowded','形容詞',2],['culture','名詞',2],['cure','動詞',2],
  ['deadline','名詞',2],['debate','名詞',2],['decrease','動詞',2],['defeat','動詞',2],
  ['definition','名詞',2],['democracy','名詞',2],['describe','動詞',2],['deserve','動詞',2],
  ['devote','動詞',2],['diary','名詞',2],['direction','名詞',2],['disaster','名詞',2],
  ['discount','名詞',2],['display','動詞',2],['donate','動詞',2],['downtown','副詞',2],
  ['duty','名詞',2],['earthquake','名詞',2],['economy','名詞',2],['election','名詞',2],
  ['electric','形容詞',2],['emergency','名詞',2],['employee','名詞',2],['environment','名詞',2],
  ['equipment','名詞',2],['eventually','副詞',2],['everywhere','副詞',2],['examine','動詞',2],
  ['exhibition','名詞',2],['expert','名詞',2],['explosion','名詞',2],['expression','名詞',2],
  ['extension','名詞',2],['extremely','副詞',2],['failure','名詞',2],['false','形容詞',2],
  ['fantasy','名詞',2],['farewell','名詞',2],['fashion','名詞',2],['feature','名詞',2],
  ['fever','名詞',2],['fiction','名詞',2],['fierce','形容詞',2],['flexible','形容詞',2],
  ['fluent','形容詞',2],['fluently','副詞',2],['forgive','動詞',2],['fountain','名詞',2],
  ['fragile','形容詞',2],['freedom','名詞',2],['frequent','形容詞',2],['frustrated','形容詞',2],
  ['furniture','名詞',2],['garbage','名詞',2],['generally','副詞',2],['generation','名詞',2],
  ['gesture','名詞',2],['grab','動詞',2],['gradual','形容詞',2],['graphic','形容詞',2],
  ['grateful','形容詞',2],['hardship','名詞',2],['harvest','名詞',2],['headline','名詞',2],
  ['homeless','形容詞',2],['hopeful','形容詞',2],['horrible','形容詞',2],['housework','名詞',2],
  ['human','形容詞',2],['hurricane','名詞',2],['hygiene','名詞',2],['ideal','形容詞',2],
  ['immediate','形容詞',2],['immigrant','名詞',2],['income','名詞',2],['independence','名詞',2],
  ['individual','形容詞',2],['infant','名詞',2],['ingredient','名詞',2],['insist','動詞',2],
  ['inspire','動詞',2],['institution','名詞',2],['intelligent','形容詞',2],['intention','名詞',2],
  ['interactive','形容詞',2],['international','形容詞',2],['interrupt','動詞',2],['introduction','名詞',2],
  ['jealous','形容詞',2],['journalist','名詞',2],['justice','名詞',2],['kindness','名詞',2],
  ['knowledge','名詞',2],['label','名詞',2],['landscape','名詞',2],['lately','副詞',2],
  ['laughter','名詞',2],['library','名詞',2],['lifestyle','名詞',2],['literature','名詞',2],
  ['local','形容詞',2],['logical','形容詞',2],['magazine','名詞',2],['magnificent','形容詞',2],
  ['major','形容詞',2],['manager','名詞',2],['maximum','形容詞',2],['meanwhile','副詞',2],
  ['medicine','名詞',2],['memory','名詞',2],['method','名詞',2],['minimum','形容詞',2],
  ['minor','形容詞',2],['miracle','名詞',2],['mist','名詞',2],['mixture','名詞',2],
  ['mobile','形容詞',2],['moderate','形容詞',2],['moreover','副詞',2],['motivation','名詞',2],
  ['multiple','形容詞',2],['musician','名詞',2],['mystery','名詞',2],['narrow','形容詞',2],
  ['national','形容詞',2],['network','名詞',2],['nonsense','名詞',2],['numerous','形容詞',2],
  ['obviously','副詞',2],['official','形容詞',2],['operation','名詞',2],['ordinary','形容詞',2],
  ['organization','名詞',2],['outstanding','形容詞',2],['overcome','動詞',2],['owe','動詞',2],
  ['paragraph','名詞',2],['patience','名詞',2],['pattern','名詞',2],['peaceful','形容詞',2],
  ['percentage','名詞',2],['permission','名詞',2],['persuade','動詞',2],['phenomenon','名詞',2],
  ['philosophy','名詞',2],['photography','名詞',2],['politician','名詞',2],['polluted','形容詞',2],
  ['population','名詞',2],['position','名詞',2],['poverty','名詞',2],['prediction','名詞',2],
  ['principle','名詞',2],['priority','名詞',2],['progress','名詞',2],['property','名詞',2],
  ['proposal','名詞',2],['protest','動詞',2],['psychology','名詞',2],['public','形容詞',2],
  ['purpose','名詞',2],['qualification','名詞',2],['questionnaire','名詞',2],['radiation','名詞',2],
  ['reaction','名詞',2],['recommendation','名詞',2],['recreation','名詞',2],['region','名詞',2],
  ['relative','名詞',2],['reliable','形容詞',2],['religion','名詞',2],['remind','動詞',2],
  ['represent','動詞',2],['rescue','動詞',2],['reserve','動詞',2],['resident','名詞',2],
  ['revolution','名詞',2],['ridiculous','形容詞',2],['ritual','名詞',2],['rough','形容詞',2],
  ['routine','名詞',2],['scenery','名詞',2],['scholarship','名詞',2],['sculpture','名詞',2],
  ['selfie','名詞',2],['semester','名詞',2],['senior','形容詞',2],['sensitive','形容詞',2],
  ['signature','名詞',2],['significant','形容詞',2],['silence','名詞',2],['similar','形容詞',2],
  ['sincerely','副詞',2],['slogan','名詞',2],['solve','動詞',2],['sophomore','名詞',2],
  ['source','名詞',2],['species','名詞',2],['stadium','名詞',2],['strategy','名詞',2],
  ['struggle','動詞',2],['substitute','動詞',2],['suitable','形容詞',2],['summary','名詞',2],
  ['supply','動詞',2],['suppose','動詞',2],['surface','名詞',2],['sustainable','形容詞',2],
  ['talent','名詞',2],['temporary','形容詞',2],['tension','名詞',2],['text','名詞',2],
  ['theme','名詞',2],['theory','名詞',2],['thousand','數詞',2],['throughout','介系詞',2],
  ['tidy','形容詞',2],['topic','名詞',2],['transport','動詞',2],['treasure','名詞',2],
  ['trial','名詞',2],['tropical','形容詞',2],['unique','形容詞',2],['universe','名詞',2],
  ['upload','動詞',2],['urban','形容詞',2],['useful','形容詞',2],['version','名詞',2],
  ['victim','名詞',2],['virus','名詞',2],['vision','名詞',2],['vocabulary','名詞',2],
  ['volcano','名詞',2],['warehouse','名詞',2],['welfare','名詞',2],['wildlife','名詞',2],
  ['witness','名詞',2],['wonder','動詞',2],['worldwide','副詞',2],['worship','動詞',2],

  // ── 補充：數字、顏色、身體、動物、食物、交通、家居、學校、職業、科技、自然、時間、情緒、衣服、運動、健康、社會 ──
  ['zero','數詞',1],['hundred','數詞',1],['million','數詞',2],['half','形容詞',1],
  ['both','形容詞',1],['once','副詞',1],['twice','副詞',1],['dozen','數詞',2],
  ['percent','名詞',2],['total','形容詞',1],['average','名詞',2],
  ['red','形容詞',1],['blue','形容詞',1],['green','形容詞',1],['yellow','形容詞',1],
  ['orange','形容詞',1],['purple','形容詞',1],['pink','形容詞',1],['white','形容詞',1],
  ['black','形容詞',1],['gray','形容詞',1],['brown','形容詞',1],['gold','形容詞',2],
  ['silver','形容詞',2],['circle','名詞',1],['square','名詞',1],['triangle','名詞',1],
  ['rectangle','名詞',2],['round','形容詞',1],['flat','形容詞',1],['straight','形容詞',1],
  ['thick','形容詞',1],['thin','形容詞',1],['heavy','形容詞',1],['light','形容詞',1],
  ['smooth','形容詞',1],['soft','形容詞',1],
  ['head','名詞',1],['hair','名詞',1],['eye','名詞',1],['ear','名詞',1],
  ['nose','名詞',1],['mouth','名詞',1],['tooth','名詞',1],['lip','名詞',1],
  ['neck','名詞',1],['shoulder','名詞',1],['arm','名詞',1],['elbow','名詞',1],
  ['hand','名詞',1],['finger','名詞',1],['thumb','名詞',1],['chest','名詞',1],
  ['stomach','名詞',1],['leg','名詞',1],['knee','名詞',1],['foot','名詞',1],
  ['toe','名詞',1],['bone','名詞',1],['muscle','名詞',2],['skin','名詞',1],
  ['blood','名詞',1],['throat','名詞',1],['forehead','名詞',2],['cheek','名詞',1],
  ['chin','名詞',1],['tongue','名詞',1],
  ['dog','名詞',1],['cat','名詞',1],['horse','名詞',1],['cow','名詞',1],
  ['pig','名詞',1],['sheep','名詞',1],['chicken','名詞',1],['duck','名詞',1],
  ['rabbit','名詞',1],['tiger','名詞',1],['lion','名詞',1],['elephant','名詞',1],
  ['bear','名詞',1],['wolf','名詞',1],['fox','名詞',1],['monkey','名詞',1],
  ['panda','名詞',1],['deer','名詞',1],['giraffe','名詞',1],['snake','名詞',1],
  ['frog','名詞',1],['turtle','名詞',1],['crocodile','名詞',2],['whale','名詞',1],
  ['dolphin','名詞',1],['shark','名詞',1],['penguin','名詞',1],['eagle','名詞',1],
  ['parrot','名詞',1],['butterfly','名詞',1],['bee','名詞',1],['ant','名詞',1],
  ['spider','名詞',1],['mosquito','名詞',1],['dragon','名詞',1],['dinosaur','名詞',1],
  ['hamster','名詞',1],['goldfish','名詞',1],['peacock','名詞',2],
  ['rice','名詞',1],['noodle','名詞',1],['soup','名詞',1],['meat','名詞',1],
  ['beef','名詞',1],['pork','名詞',1],['seafood','名詞',1],['shrimp','名詞',1],
  ['crab','名詞',1],['egg','名詞',1],['tofu','名詞',1],['vegetable','名詞',1],
  ['fruit','名詞',1],['apple','名詞',1],['banana','名詞',1],['grape','名詞',1],
  ['strawberry','名詞',1],['watermelon','名詞',1],['mango','名詞',1],['peach','名詞',1],
  ['lemon','名詞',1],['pear','名詞',1],['pineapple','名詞',1],['tomato','名詞',1],
  ['potato','名詞',1],['carrot','名詞',1],['onion','名詞',1],['garlic','名詞',1],
  ['mushroom','名詞',1],['corn','名詞',1],['salad','名詞',1],['pizza','名詞',1],
  ['hamburger','名詞',1],['sandwich','名詞',1],['cookie','名詞',1],['candy','名詞',1],
  ['chocolate','名詞',1],['juice','名詞',1],['milk','名詞',1],['coffee','名詞',1],
  ['sauce','名詞',1],['butter','名詞',1],['cheese','名詞',1],['flour','名詞',1],
  ['salt','名詞',1],['oil','名詞',1],['recipe','名詞',2],['menu','名詞',1],
  ['dish','名詞',1],['snack','名詞',1],['breakfast','名詞',1],['meal','名詞',1],
  ['dessert','名詞',1],
  ['car','名詞',1],['bus','名詞',1],['plane','名詞',1],['ship','名詞',1],
  ['boat','名詞',1],['bike','名詞',1],['truck','名詞',1],['taxi','名詞',1],
  ['subway','名詞',1],['motorcycle','名詞',1],['helicopter','名詞',1],
  ['airport','名詞',1],['station','名詞',1],['port','名詞',1],['highway','名詞',1],
  ['road','名詞',1],['path','名詞',1],['tunnel','名詞',1],['traffic','名詞',1],
  ['map','名詞',1],['north','名詞',1],['south','名詞',1],['east','名詞',1],
  ['west','名詞',1],['corner','名詞',1],['block','名詞',1],['hospital','名詞',1],
  ['pharmacy','名詞',2],['supermarket','名詞',1],['restaurant','名詞',1],
  ['museum','名詞',1],['zoo','名詞',1],['theater','名詞',1],['church','名詞',1],
  ['temple','名詞',1],['palace','名詞',2],['factory','名詞',1],['farm','名詞',1],
  ['forest','名詞',1],['desert','名詞',1],['river','名詞',1],['lake','名詞',1],
  ['sea','名詞',1],['coast','名詞',1],['hill','名詞',1],['valley','名詞',1],
  ['cave','名詞',1],['waterfall','名詞',1],
  ['apartment','名詞',1],['bedroom','名詞',1],['bathroom','名詞',1],['kitchen','名詞',1],
  ['window','名詞',1],['wall','名詞',1],['roof','名詞',1],['stair','名詞',1],
  ['elevator','名詞',1],['gate','名詞',1],['fence','名詞',1],['sofa','名詞',1],
  ['chair','名詞',1],['bed','名詞',1],['desk','名詞',1],['shelf','名詞',1],
  ['drawer','名詞',1],['lamp','名詞',1],['mirror','名詞',1],['blanket','名詞',1],
  ['pillow','名詞',1],['curtain','名詞',1],['carpet','名詞',1],['refrigerator','名詞',1],
  ['microwave','名詞',1],['oven','名詞',1],['stove','名詞',1],['fan','名詞',1],
  ['television','名詞',1],['key','名詞',1],['lock','名詞',1],['trash','名詞',1],
  ['pencil','名詞',1],['pen','名詞',1],['eraser','名詞',1],['ruler','名詞',1],
  ['notebook','名詞',1],['textbook','名詞',1],['dictionary','名詞',1],['scissors','名詞',1],
  ['glue','名詞',1],['marker','名詞',1],['blackboard','名詞',1],['chalk','名詞',1],
  ['projector','名詞',1],['computer','名詞',1],['printer','名詞',1],['exam','名詞',1],
  ['test','名詞',1],['essay','名詞',1],['biology','名詞',2],['chemistry','名詞',2],
  ['physics','名詞',2],['geography','名詞',2],['principal','名詞',1],['professor','名詞',1],
  ['lecture','名詞',2],['tutor','名詞',2],['graduate','動詞',2],['enroll','動詞',2],
  ['presentation','名詞',2],
  ['doctor','名詞',1],['nurse','名詞',1],['lawyer','名詞',1],['engineer','名詞',1],
  ['scientist','名詞',1],['artist','名詞',1],['actor','名詞',1],['writer','名詞',1],
  ['farmer','名詞',1],['soldier','名詞',1],['police','名詞',1],['firefighter','名詞',1],
  ['chef','名詞',1],['driver','名詞',1],['pilot','名詞',1],['cashier','名詞',1],
  ['architect','名詞',2],['dentist','名詞',1],['accountant','名詞',2],['secretary','名詞',1],
  ['boss','名詞',1],['colleague','名詞',2],['salary','名詞',2],['interview','名詞',1],
  ['workplace','名詞',2],['retire','動詞',2],
  ['website','名詞',1],['app','名詞',1],['software','名詞',1],['hardware','名詞',2],
  ['robot','名詞',1],['camera','名詞',1],['video','名詞',1],['screen','名詞',1],
  ['keyboard','名詞',1],['charger','名詞',1],['cable','名詞',1],['wireless','形容詞',2],
  ['password','名詞',1],['download','動詞',1],['post','動詞',1],['comment','名詞',1],
  ['subscribe','動詞',2],['satellite','名詞',2],['artificial','形容詞',2],
  ['database','名詞',2],['server','名詞',2],['signal','名詞',2],
  ['sun','名詞',1],['moon','名詞',1],['star','名詞',1],['sky','名詞',1],
  ['wind','名詞',1],['snow','名詞',1],['ice','名詞',1],['storm','名詞',1],
  ['thunder','名詞',1],['lightning','名詞',1],['fog','名詞',1],['rainbow','名詞',1],
  ['flood','名詞',1],['drought','名詞',2],['tornado','名詞',2],['tsunami','名詞',2],
  ['soil','名詞',1],['rock','名詞',1],['sand','名詞',1],['mud','名詞',1],
  ['seed','名詞',1],['leaf','名詞',1],['root','名詞',1],['petal','名詞',1],
  ['grass','名詞',1],['jungle','名詞',1],['oxygen','名詞',2],['carbon','名詞',2],
  ['solar','形容詞',2],['fossil','名詞',2],['ecology','名詞',2],
  ['minute','名詞',1],['hour','名詞',1],['decade','名詞',2],['century','名詞',2],
  ['spring','名詞',1],['autumn','名詞',1],['winter','名詞',1],['sunrise','名詞',1],
  ['sunset','名詞',1],['midnight','名詞',1],['dawn','名詞',2],['noon','名詞',1],
  ['dusk','名詞',2],['era','名詞',2],['past','名詞',1],['ancient','形容詞',1],
  ['current','形容詞',2],['latest','形容詞',2],['permanent','形容詞',2],
  ['forever','副詞',1],['immediately','副詞',2],
  ['hate','動詞',1],['joy','名詞',1],['sadness','名詞',1],['anger','名詞',1],
  ['pride','名詞',2],['shame','名詞',2],['envy','名詞',2],['guilt','名詞',2],
  ['stress','名詞',1],['anxiety','名詞',2],['depression','名詞',2],['confidence','名詞',1],
  ['boredom','名詞',2],['excitement','名詞',2],['loneliness','名詞',2],['happiness','名詞',1],
  ['misery','名詞',2],['frustration','名詞',2],['relief','名詞',2],
  ['shirt','名詞',1],['pants','名詞',1],['dress','名詞',1],['skirt','名詞',1],
  ['jacket','名詞',1],['coat','名詞',1],['sweater','名詞',1],['uniform','名詞',1],
  ['shoe','名詞',1],['boot','名詞',1],['socks','名詞',1],['hat','名詞',1],
  ['scarf','名詞',1],['glove','名詞',1],['belt','名詞',1],['ring','名詞',1],
  ['necklace','名詞',1],['earring','名詞',1],['bracelet','名詞',1],['pocket','名詞',1],
  ['zipper','名詞',1],['sleeve','名詞',1],['style','名詞',1],['trend','名詞',2],
  ['brand','名詞',2],['handsome','形容詞',1],['ugly','形容詞',1],['elegant','形容詞',2],
  ['neat','形容詞',1],['messy','形容詞',1],['casual','形容詞',2],
  ['soccer','名詞',1],['basketball','名詞',1],['baseball','名詞',1],['tennis','名詞',1],
  ['badminton','名詞',1],['volleyball','名詞',1],['cycling','名詞',1],['hiking','名詞',1],
  ['camping','名詞',1],['fishing','名詞',1],['bowling','名詞',1],['golf','名詞',2],
  ['trophy','名詞',1],['tournament','名詞',2],['referee','名詞',2],['cheer','動詞',1],
  ['firework','名詞',1],['carnival','名詞',2],['magic','名詞',1],
  ['medicine','名詞',2],['pill','名詞',1],['injection','名詞',2],['surgery','名詞',2],
  ['symptom','名詞',2],['fever','名詞',2],['cough','名詞',1],['allergy','名詞',2],
  ['injury','名詞',2],['wound','名詞',2],['bandage','名詞',2],['ambulance','名詞',2],
  ['vaccine','名詞',2],['nutrition','名詞',2],['vitamin','名詞',2],['calorie','名詞',2],
  ['protein','名詞',2],['jog','動詞',1],['stretch','動詞',1],['meditate','動詞',2],
  ['mask','名詞',1],['thermometer','名詞',2],['prescription','名詞',2],
  ['ceremony','名詞',2],['custom','名詞',2],['heritage','名詞',2],['belief','名詞',2],
  ['prayer','名詞',2],['myth','名詞',2],['legend','名詞',2],['folktale','名詞',2],
  ['movement','名詞',2],['reform','名詞',2],['refugee','名詞',2],['diversity','名詞',2],
  ['inclusion','名詞',2],

  // ── 官方 MoE 2000字補充 (PDF 驗證新增) ──────────────────────────────
['about','介系詞',1],
  ['absent','形容詞',1],
  ['across','介系詞',1],
  ['act','名詞',1],
  ['actress','名詞',1],
  ['admire','動詞',1],
  ['advertisement','名詞',1],
  ['advise','動詞',1],
  ['airplane','名詞',1],
  ['alarm','名詞',1],
  ['alike','副詞',1],
  ['all','形容詞',1],
  ['along','介系詞',1],
  ['aloud','副詞',1],
  ['altogether','副詞',1],
  ['among','介系詞',1],
  ['angel','名詞',1],
  ['ankle','名詞',1],
  ['any','形容詞',1],
  ['april','名詞',1],
  ['armchair','名詞',1],
  ['army','名詞',1],
  ['as','介系詞',1],
  ['asleep','形容詞',1],
  ['assistant','名詞',1],
  ['assume','動詞',1],
  ['august','名詞',1],
  ['bake','動詞',1],
  ['bakery','名詞',1],
  ['balcony','名詞',1],
  ['ball','名詞',1],
  ['balloon','名詞',1],
  ['band','名詞',1],
  ['barbecue','動詞',1],
  ['barber','名詞',1],
  ['bark','動詞',1],
  ['basement','名詞',1],
  ['basic','形容詞',1],
  ['basket','名詞',1],
  ['bat','名詞',1],
  ['bathe','動詞',1],
  ['bean','名詞',1],
  ['beard','名詞',1],
  ['beat','動詞',1],
  ['beauty','名詞',1],
  ['beer','名詞',1],
  ['beginner','名詞',1],
  ['beginning','名詞',1],
  ['behave','動詞',1],
  ['behind','副詞',1],
  ['bell','名詞',1],
  ['below','副詞',1],
  ['bench','名詞',1],
  ['besides','副詞',1],
  ['bill','名詞',1],
  ['bite','動詞',1],
  ['bitter','形容詞',1],
  ['blame','動詞',1],
  ['blind','形容詞',1],
  ['bloody','形容詞',1],
  ['blow','動詞',1],
  ['boil','動詞',1],
  ['bomb','名詞',1],
  ['bookcase','名詞',1],
  ['bored','形容詞',1],
  ['born','形容詞',1],
  ['borrow','動詞',1],
  ['bottle','名詞',1],
  ['bottom','名詞',1],
  ['bow','名詞',1],
  ['bowl','名詞',1],
  ['boy','名詞',1],
  ['brick','名詞',1],
  ['brief','形容詞',1],
  ['broad','形容詞',1],
  ['brunch','名詞',1],
  ['brush','名詞',1],
  ['bucket','名詞',1],
  ['buffet','名詞',1],
  ['bug','名詞',1],
  ['building','名詞',1],
  ['bun','名詞',1],
  ['bundle','名詞',1],
  ['burn','動詞',1],
  ['burst','動詞',1],
  ['business','名詞',1],
  ['businessman','名詞',1],
  ['but','連接詞',1],
  ['cabbage','名詞',1],
  ['cage','名詞',1],
  ['cake','名詞',1],
  ['camp','動詞',1],
  ['cancer','名詞',1],
  ['candle','名詞',1],
  ['cap','名詞',1],
  ['card','名詞',1],
  ['cartoon','名詞',1],
  ['case','名詞',1],
  ['cash','名詞',1],
  ['cassette','名詞',1],
  ['cell','名詞',1],
  ['cent','名詞',1],
  ['center','名詞',1],
  ['centimeter','名詞',1],
  ['central','形容詞',1],
  ['cereal','名詞',1],
  ['channel','名詞',1],
  ['charge','動詞',1],
  ['chase','動詞',1],
  ['cheap','形容詞',1],
  ['cheat','動詞',1],
  ['chess','名詞',1],
  ['chief','名詞',1],
  ['childish','形容詞',1],
  ['childlike','形容詞',1],
  ['chopstick','名詞',1],
  ['christmas','名詞',1],
  ['chubby','形容詞',1],
  ['classic','形容詞',1],
  ['classmate','名詞',1],
  ['clay','名詞',1],
  ['clock','副詞',1],
  ['closet','名詞',1],
  ['club','名詞',1],
  ['cockroach','名詞',1],
  ['coin','名詞',1],
  ['coke','名詞',1],
  ['colorful','形容詞',1],
  ['comb','名詞',1],
  ['common','形容詞',1],
  ['company','名詞',1],
  ['concern','名詞',1],
  ['conflict','名詞',1],
  ['congratulation','名詞',1],
  ['considerate','形容詞',1],
  ['contract','名詞',1],
  ['cotton','名詞',1],
  ['couch','名詞',1],
  ['count','動詞',1],
  ['couple','名詞',1],
  ['course','名詞',1],
  ['court','名詞',1],
  ['cowboy','名詞',1],
  ['crayon','名詞',1],
  ['crazy','形容詞',1],
  ['cream','名詞',1],
  ['cruel','形容詞',1],
  ['curve','名詞',1],
  ['cute','形容詞',1],
  ['dangerous','形容詞',1],
  ['data','名詞',1],
  ['date','名詞',1],
  ['daughter','名詞',1],
  ['dead','形容詞',1],
  ['death','名詞',1],
  ['december','名詞',1],
  ['decision','名詞',1],
  ['decorate','動詞',1],
  ['delicious','形容詞',1],
  ['deny','動詞',1],
  ['department','名詞',1],
  ['depend','動詞',1],
  ['desire','名詞',2],
  ['detect','動詞',2],
  ['dial','動詞',1],
  ['diamond','名詞',2],
  ['die','動詞',1],
  ['difference','名詞',1],
  ['difficulty','名詞',1],
  ['dig','動詞',1],
  ['diligent','形容詞',1],
  ['diplomat','名詞',1],
  ['direct','形容詞',2],
  ['disagree','動詞',1],
  ['discussion','名詞',1],
  ['dishonest','形容詞',1],
  ['distant','形容詞',1],
  ['dizzy','形容詞',1],
  ['doll','名詞',1],
  ['dollar','名詞',1],
  ['donkey','名詞',1],
  ['dot','名詞',2],
  ['doughnut','名詞',2],
  ['dove','名詞',2],
  ['downstairs','副詞',2],
  ['drag','動詞',2],
  ['drama','名詞',2],
  ['drug','名詞',2],
  ['drum','名詞',1],
  ['dry','形容詞',1],
  ['dryer','名詞',2],
  ['dumb','形容詞',2],
  ['dumpling','名詞',2],
  ['earn','動詞',1],
  ['ease','動詞',2],
  ['eastern','形容詞',2],
  ['edge','名詞',1],
  ['eight','名詞',1],
  ['eighteen','名詞',1],
  ['eighty','名詞',1],
  ['elder','形容詞',2],
  ['elect','動詞',2],
  ['eleven','名詞',1],
  ['embarrass','動詞',2],
  ['emphasize','動詞',2],
  ['employ','動詞',2],
  ['empty','形容詞',1],
  ['end','動詞',1],
  ['energetic','形容詞',2],
  ['entrance','名詞',2],
  ['envelope','名詞',2],
  ['equal','形容詞',2],
  ['error','名詞',2],
  ['eve','名詞',2],
  ['evil','名詞',2],
  ['except','介系詞',2],
  ['excite','動詞',2],
  ['excuse','動詞',1],
  ['exit','名詞',2],
  ['expensive','形容詞',2],
  ['eyebrow','名詞',2],
  ['fact','名詞',1],
  ['fancy','名詞',2],
  ['fat','形容詞',1],
  ['father','名詞',1],
  ['faucet','名詞',1],
  ['fault','名詞',1],
  ['february','名詞',1],
  ['fee','名詞',1],
  ['feed','動詞',1],
  ['feeling','名詞',1],
  ['fifteen','名詞',1],
  ['fifty','名詞',1],
  ['fight','名詞',1],
  ['fill','動詞',1],
  ['final','形容詞',1],
  ['fine','形容詞',1],
  ['first','形容詞',1],
  ['fisherman','名詞',2],
  ['five','名詞',1],
  ['flag','名詞',1],
  ['flash','名詞',2],
  ['flashlight','名詞',2],
  ['flight','名詞',1],
  ['flu','名詞',1],
  ['flute','名詞',1],
  ['fool','名詞',1],
  ['foolish','形容詞',1],
  ['football','名詞',1],
  ['for','介系詞',1],
  ['foreigner','名詞',2],
  ['fork','名詞',1],
  ['form','動詞',1],
  ['former','形容詞',1],
  ['forty','名詞',1],
  ['four','名詞',1],
  ['fourteen','名詞',1],
  ['frank','形容詞',2],
  ['friday','名詞',1],
  ['frighten','動詞',2],
  ['front','形容詞',1],
  ['fry','動詞',1],
  ['funny','形容詞',1],
  ['gain','動詞',2],
  ['garage','名詞',2],
  ['gas','名詞',2],
  ['gather','動詞',2],
  ['general','形容詞',2],
  ['generous','形容詞',2],
  ['genius','名詞',2],
  ['gentle','形容詞',2],
  ['gentleman','名詞',2],
  ['ghost','名詞',2],
  ['giant','形容詞',2],
  ['girl','名詞',1],
  ['glass','名詞',1],
  ['glasses','名詞',1],
  ['go','動詞',1],
  ['goat','名詞',1],
  ['god','名詞',1],
  ['golden','形容詞',2],
  ['goodness','名詞',2],
  ['goose','名詞',2],
  ['gram','名詞',2],
  ['grandfather','名詞',1],
  ['grandmother','名詞',1],
  ['grandson','名詞',2],
  ['greedy','形容詞',2],
  ['greet','動詞',2],
  ['ground','名詞',1],
  ['guava','名詞',1],
  ['guest','名詞',1],
  ['guitar','名詞',1],
  ['gun','名詞',1],
  ['guy','名詞',2],
  ['hall','名詞',2],
  ['halloween','名詞',1],
  ['ham','名詞',2],
  ['hammer','名詞',2],
  ['handkerchief','名詞',2],
  ['hang','動詞',1],
  ['hanger','名詞',2],
  ['hardly','副詞',1],
  ['headache','名詞',2],
  ['healthy','形容詞',1],
  ['heat','名詞',1],
  ['heater','名詞',2],
  ['height','名詞',1],
  ['hen','名詞',2],
  ['hide','動詞',1],
  ['high','形容詞',1],
  ['hike','名詞',1],
  ['hip','名詞',2],
  ['hippo','名詞',2],
  ['hit','動詞',1],
  ['hole','名詞',1],
  ['honesty','名詞',2],
  ['honey','名詞',1],
  ['hop','名詞',2],
  ['host','名詞',2],
  ['hot','形容詞',1],
  ['housewife','名詞',2],
  ['how','副詞',1],
  ['humid','形容詞',2],
  ['humorous','形容詞',2],
  ['hunt','動詞',2],
  ['hunter','名詞',2],
  ['hurry','動詞',2],
  ['husband','名詞',1],
  ['if','連接詞',1],
  ['ill','形容詞',1],
  ['impolite','形容詞',2],
  ['importance','名詞',2],
  ['impossible','形容詞',2],
  ['in','介系詞',1],
  ['inch','名詞',2],
  ['independent','形容詞',1],
  ['indicate','動詞',2],
  ['information','名詞',2],
  ['ink','名詞',1],
  ['insect','名詞',2],
  ['inside','副詞',1],
  ['instance','名詞',2],
  ['instant','形容詞',2],
  ['instrument','名詞',2],
  ['interesting','形容詞',1],
  ['into','介系詞',1],
  ['invitation','名詞',1],
  ['iron','名詞',2],
  ['item','名詞',2],
  ['jam','名詞',1],
  ['january','名詞',1],
  ['jazz','名詞',2],
  ['jeans','名詞',1],
  ['jeep','名詞',2],
  ['job','名詞',1],
  ['joke','名詞',1],
  ['july','名詞',1],
  ['june','名詞',1],
  ['ketchup','名詞',1],
  ['kick','動詞',1],
  ['kid','名詞',1],
  ['kill','動詞',1],
  ['kilogram','名詞',2],
  ['kilometer','名詞',2],
  ['kindergarten','名詞',2],
  ['king','名詞',1],
  ['kingdom','名詞',2],
  ['kiss','名詞',1],
  ['kite','名詞',1],
  ['kitten','名詞',2],
  ['knife','名詞',1],
  ['knock','動詞',1],
  ['lady','名詞',1],
  ['lamb','名詞',1],
  ['land','名詞',1],
  ['lantern','名詞',2],
  ['large','形容詞',1],
  ['later','形容詞',1],
  ['lay','動詞',1],
  ['lazy','形容詞',1],
  ['lead','動詞',1],
  ['least','副詞',1],
  ['left','形容詞',1],
  ['legal','形容詞',1],
  ['lend','動詞',1],
  ['less','形容詞',1],
  ['lesson','名詞',1],
  ['let','動詞',1],
  ['lettuce','名詞',1],
  ['level','名詞',1],
  ['lick','動詞',2],
  ['lid','名詞',2],
  ['lie','名詞',1],
  ['lift','動詞',1],
  ['likely','副詞',2],
  ['lily','名詞',2],
  ['limit','名詞',1],
  ['line','名詞',1],
  ['link','名詞',2],
  ['liquid','名詞',2],
  ['list','動詞',1],
  ['liter','名詞',2],
  ['little','形容詞',1],
  ['loaf','名詞',2],
  ['locker','名詞',2],
  ['lose','動詞',1],
  ['loser','名詞',2],
  ['lot','名詞',1],
  ['lover','名詞',2],
  ['low','形容詞',1],
  ['luck','名詞',1],
  ['machine','名詞',2],
  ['mad','形容詞',2],
  ['magician','名詞',2],
  ['mail','名詞',1],
  ['maintain','動詞',2],
  ['male','名詞',2],
  ['mall','名詞',2],
  ['man','名詞',1],
  ['march','名詞',1],
  ['mark','名詞',1],
  ['marriage','名詞',1],
  ['married','形容詞',1],
  ['marry','動詞',1],
  ['marvelous','形容詞',2],
  ['mass','名詞',2],
  ['master','名詞',2],
  ['mat','名詞',2],
  ['match','名詞',1],
  ['mate','名詞',2],
  ['matter','名詞',1],
  ['may','助動詞',1],
  ['meaning','名詞',2],
  ['measure','動詞',1],
  ['mechanic','名詞',2],
  ['medium','形容詞',2],
  ['meeting','名詞',1],
  ['member','名詞',1],
  ['metal','名詞',1],
  ['meter','名詞',2],
  ['middle','形容詞',1],
  ['mile','名詞',2],
  ['mine','名詞',1],
  ['minus','介系詞',2],
  ['mix','動詞',2],
  ['model','名詞',2],
  ['monday','名詞',1],
  ['monster','名詞',2],
  ['mop','名詞',2],
  ['mother','名詞',1],
  ['motion','名詞',2],
  ['mouse','名詞',1],
  ['movie','名詞',1],
  ['mug','名詞',2],
  ['nail','名詞',1],
  ['name','名詞',1],
  ['napkin','名詞',2],
  ['nation','名詞',1],
  ['naughty','形容詞',2],
  ['near','形容詞',1],
  ['nearly','副詞',1],
  ['needle','名詞',2],
  ['neither','副詞',2],
  ['nephew','名詞',2],
  ['nest','名詞',2],
  ['new','形容詞',1],
  ['news','名詞',1],
  ['newspaper','名詞',1],
  ['niece','名詞',1],
  ['nine','名詞',1],
  ['nineteen','名詞',1],
  ['ninety','名詞',1],
  ['no','副詞',1],
  ['nod','動詞',2],
  ['noisy','形容詞',2],
  ['none','代名詞',2],
  ['nor','連接詞',1],
  ['not','副詞',1],
  ['note','名詞',2],
  ['nothing','代名詞',1],
  ['november','名詞',1],
  ['nut','名詞',2],
  ['object','名詞',2],
  ['october','名詞',1],
  ['of','介系詞',1],
  ['off','介系詞',1],
  ['offer','動詞',1],
  ['officer','名詞',1],
  ['okay','形容詞',1],
  ['omit','動詞',2],
  ['on','介系詞',1],
  ['one','形容詞',1],
  ['operate','動詞',2],
  ['or','連接詞',1],
  ['organ','名詞',2],
  ['out','副詞',1],
  ['over','介系詞',1],
  ['overseas','副詞',2],
  ['owner','名詞',2],
  ['ox','名詞',2],
  ['pack','動詞',1],
  ['package','名詞',2],
  ['pain','名詞',1],
  ['paint','動詞',1],
  ['painter','名詞',1],
  ['pair','名詞',1],
  ['pajamas','名詞',2],
  ['pale','形容詞',2],
  ['pan','名詞',2],
  ['papaya','名詞',2],
  ['paper','名詞',1],
  ['pardon','名詞',2],
  ['party','名詞',1],
  ['passenger','名詞',2],
  ['paste','名詞',2],
  ['pause','名詞',2],
  ['peace','名詞',1],
  ['peanut','名詞',2],
  ['pepper','名詞',1],
  ['perfect','形容詞',2],
  ['perhaps','副詞',1],
  ['pet','名詞',1],
  ['piano','名詞',1],
  ['picnic','名詞',1],
  ['pie','名詞',1],
  ['piece','名詞',1],
  ['pigeon','名詞',2],
  ['pile','名詞',2],
  ['pin','名詞',2],
  ['pipe','名詞',2],
  ['plain','名詞',2],
  ['plate','名詞',1],
  ['platform','名詞',2],
  ['player','名詞',1],
  ['playground','名詞',1],
  ['pleasant','形容詞',2],
  ['plus','介系詞',2],
  ['poet','名詞',2],
  ['point','動詞',1],
  ['poison','名詞',2],
  ['pollution','名詞',2],
  ['pond','名詞',2],
  ['pool','名詞',1],
  ['poor','形容詞',1],
  ['popcorn','名詞',2],
  ['pose','名詞',2],
  ['pot','名詞',2],
  ['pound','名詞',2],
  ['powder','名詞',2],
  ['power','名詞',1],
  ['praise','名詞',2],
  ['pray','動詞',2],
  ['precious','形容詞',2],
  ['prefer','動詞',2],
  ['presence','名詞',2],
  ['president','名詞',1],
  ['priest','名詞',2],
  ['primary','形容詞',2],
  ['prince','名詞',2],
  ['princess','名詞',2],
  ['print','動詞',1],
  ['prison','名詞',2],
  ['private','形容詞',2],
  ['prize','名詞',1],
  ['probably','副詞',1],
  ['production','名詞',1],
  ['pronounce','動詞',2],
  ['pull','動詞',1],
  ['pump','名詞',2],
  ['pumpkin','名詞',2],
  ['puppy','名詞',2],
  ['purse','名詞',2],
  ['push','動詞',1],
  ['puzzle','名詞',2],
  ['quantity','名詞',2],
  ['quarter','名詞',2],
  ['queen','名詞',1],
  ['quit','動詞',1],
  ['quite','副詞',1],
  ['quiz','名詞',2],
  ['race','名詞',1],
  ['radio','名詞',1],
  ['railroad','名詞',2],
  ['rainy','形容詞',2],
  ['range','名詞',2],
  ['rare','形容詞',2],
  ['rat','名詞',2],
  ['rather','副詞',2],
  ['really','副詞',1],
  ['record','名詞',2],
  ['recover','動詞',2],
  ['refuse','動詞',2],
  ['regard','動詞',2],
  ['regret','名詞',2],
  ['regular','形容詞',2],
  ['reject','動詞',2],
  ['relation','名詞',2],
  ['rent','動詞',2],
  ['reply','動詞',2],
  ['reporter','名詞',2],
  ['require','動詞',2],
  ['responsible','形容詞',2],
  ['restroom','名詞',2],
  ['revise','動詞',2],
  ['rich','形容詞',1],
  ['rise','動詞',1],
  ['rob','動詞',2],
  ['roll','動詞',1],
  ['rope','名詞',2],
  ['rose','名詞',1],
  ['row','名詞',1],
  ['royal','形容詞',2],
  ['rub','動詞',2],
  ['rubber','名詞',2],
  ['rude','形容詞',2],
  ['ruin','動詞',2],
  ['rush','動詞',2],
  ['sad','形容詞',1],
  ['safety','名詞',2],
  ['sail','動詞',2],
  ['sailor','名詞',2],
  ['sale','名詞',1],
  ['sample','名詞',2],
  ['satisfy','動詞',2],
  ['saturday','名詞',1],
  ['scare','動詞',2],
  ['scene','名詞',2],
  ['scooter','名詞',2],
  ['score','名詞',1],
  ['seat','名詞',1],
  ['secret','名詞',1],
  ['section','名詞',2],
  ['seek','動詞',2],
  ['seesaw','名詞',2],
  ['seldom','副詞',2],
  ['select','動詞',2],
  ['self','名詞',2],
  ['selfish','形容詞',2],
  ['sell','動詞',1],
  ['sense','名詞',2],
  ['sentence','名詞',1],
  ['september','名詞',1],
  ['servant','名詞',2],
  ['serve','動詞',2],
  ['service','名詞',2],
  ['set','名詞',1],
  ['seven','名詞',1],
  ['seventeen','名詞',1],
  ['seventy','名詞',1],
  ['shake','動詞',2],
  ['shall','助動詞',1],
  ['shape','名詞',2],
  ['sharp','形容詞',2],
  ['sheet','名詞',1],
  ['shell','名詞',2],
  ['shine','動詞',2],
  ['shock','名詞',2],
  ['shoot','動詞',1],
  ['shop','名詞',1],
  ['shore','名詞',1],
  ['short','形容詞',1],
  ['shorts','名詞',1],
  ['should','助動詞',1],
  ['shout','動詞',1],
  ['shower','名詞',1],
  ['shut','動詞',1],
  ['shy','形容詞',1],
  ['side','名詞',1],
  ['sidewalk','名詞',2],
  ['sight','名詞',2],
  ['sign','動詞',2],
  ['silent','形容詞',1],
  ['silk','名詞',2],
  ['silly','形容詞',1],
  ['simply','副詞',2],
  ['since','介系詞',1],
  ['sincere','形容詞',2],
  ['singer','名詞',2],
  ['single','形容詞',1],
  ['sink','動詞',1],
  ['sir','名詞',1],
  ['sitter','名詞',2],
  ['six','名詞',1],
  ['sixteen','名詞',1],
  ['sixty','名詞',1],
  ['size','名詞',2],
  ['skate','動詞',2],
  ['ski','動詞',2],
  ['skillful','形容詞',2],
  ['skinny','形容詞',2],
  ['sleepy','形容詞',2],
  ['slender','形容詞',2],
  ['slide','動詞',2],
  ['slim','形容詞',2],
  ['slippers','名詞',2],
  ['smart','形容詞',1],
  ['smell','動詞',1],
  ['smoke','名詞',1],
  ['snail','名詞',2],
  ['sneakers','名詞',2],
  ['snowy','形容詞',2],
  ['so','副詞',1],
  ['soap','名詞',1],
  ['sock','名詞',1],
  ['soda','名詞',2],
  ['some','形容詞',1],
  ['somewhere','副詞',1],
  ['son','名詞',1],
  ['song','名詞',1],
  ['sore','形容詞',2],
  ['soul','名詞',2],
  ['sound','動詞',1],
  ['sour','形容詞',2],
  ['soy','名詞',2],
  ['space','名詞',1],
  ['spaghetti','名詞',2],
  ['speaker','名詞',2],
  ['speed','名詞',2],
  ['spell','動詞',1],
  ['spoon','名詞',1],
  ['stamp','名詞',2],
  ['stand','動詞',1],
  ['state','動詞',1],
  ['stationery','名詞',2],
  ['steak','名詞',2],
  ['steal','動詞',2],
  ['steam','名詞',2],
  ['step','動詞',1],
  ['stingy','形容詞',2],
  ['stomachache','名詞',2],
  ['stone','名詞',1],
  ['strange','形容詞',2],
  ['stranger','名詞',2],
  ['straw','名詞',2],
  ['stream','名詞',2],
  ['strike','名詞',2],
  ['stupid','形容詞',2],
  ['succeed','動詞',2],
  ['successful','形容詞',2],
  ['sudden','形容詞',2],
  ['suggest','動詞',1],
  ['suit','動詞',1],
  ['sunday','名詞',1],
  ['sunny','形容詞',1],
  ['super','形容詞',1],
  ['supper','名詞',1],
  ['sure','形容詞',1],
  ['surf','動詞',2],
  ['surprised','形容詞',1],
  ['swallow','動詞',2],
  ['swan','名詞',2],
  ['sweep','動詞',2],
  ['sweet','形容詞',1],
  ['swing','動詞',2],
  ['tail','名詞',2],
  ['tale','名詞',2],
  ['talkative','形容詞',2],
  ['tangerine','名詞',2],
  ['tank','名詞',2],
  ['tape','名詞',2],
  ['task','名詞',1],
  ['taste','名詞',1],
  ['tea','名詞',1],
  ['teach','動詞',1],
  ['teapot','名詞',2],
  ['tear','名詞',1],
  ['teenager','名詞',1],
  ['telephone','名詞',1],
  ['temperature','名詞',1],
  ['ten','名詞',1],
  ['tent','名詞',2],
  ['term','名詞',1],
  ['terrific','形容詞',2],
  ['than','連接詞',1],
  ['thanksgiving','名詞',2],
  ['that','代名詞',1],
  ['there','副詞',1],
  ['these','代名詞',1],
  ['thief','名詞',2],
  ['thing','名詞',1],
  ['third','形容詞',1],
  ['thirsty','形容詞',2],
  ['thirteen','名詞',1],
  ['thirty','名詞',1],
  ['this','代名詞',1],
  ['those','代名詞',1],
  ['thought','名詞',2],
  ['three','名詞',1],
  ['throw','動詞',1],
  ['thursday','名詞',1],
  ['ticket','名詞',1],
  ['tie','名詞',1],
  ['till','連接詞',2],
  ['tiny','形容詞',2],
  ['tip','名詞',2],
  ['to','介系詞',1],
  ['toast','名詞',2],
  ['toilet','名詞',1],
  ['tool','名詞',1],
  ['toothache','名詞',2],
  ['toothbrush','名詞',2],
  ['top','名詞',1],
  ['touch','動詞',1],
  ['toward','介系詞',1],
  ['towel','名詞',1],
  ['tower','名詞',1],
  ['toy','名詞',1],
  ['trace','名詞',2],
  ['track','動詞',2],
  ['trade','名詞',2],
  ['traditional','形容詞',2],
  ['trap','名詞',2],
  ['treat','動詞',1],
  ['trick','名詞',2],
  ['trip','名詞',1],
  ['trouble','名詞',1],
  ['trousers','名詞',2],
  ['trumpet','名詞',2],
  ['tube','名詞',2],
  ['tuesday','名詞',1],
  ['turkey','名詞',2],
  ['twelve','名詞',1],
  ['twenty','名詞',1],
  ['two','名詞',1],
  ['type','動詞',2],
  ['typhoon','名詞',2],
  ['umbrella','名詞',1],
  ['under','介系詞',1],
  ['underline','動詞',2],
  ['underwear','名詞',2],
  ['unhappy','形容詞',1],
  ['university','名詞',1],
  ['up','副詞',1],
  ['upper','形容詞',2],
  ['upstairs','副詞',2],
  ['user','名詞',2],
  ['usual','形容詞',2],
  ['vacation','名詞',1],
  ['valuable','形容詞',2],
  ['vendor','名詞',2],
  ['vest','名詞',2],
  ['victory','名詞',2],
  ['vinegar','名詞',2],
  ['violin','名詞',2],
  ['visitor','名詞',2],
  ['waist','名詞',2],
  ['waiter','名詞',2],
  ['waitress','名詞',2],
  ['wake','動詞',1],
  ['wallet','名詞',2],
  ['war','名詞',2],
  ['wash','動詞',1],
  ['water','名詞',1],
  ['wave','名詞',1],
  ['weak','形容詞',1],
  ['weapon','名詞',2],
  ['wedding','名詞',2],
  ['wednesday','名詞',1],
  ['weekday','名詞',2],
  ['weekend','名詞',2],
  ['welcome','動詞',1],
  ['wet','形容詞',1],
  ['what','代名詞',1],
  ['wheel','名詞',2],
  ['which','代名詞',1],
  ['who','代名詞',1],
  ['whole','形容詞',1],
  ['whose','代名詞',1],
  ['why','副詞',1],
  ['wife','名詞',2],
  ['windy','形容詞',2],
  ['wine','名詞',2],
  ['wing','名詞',1],
  ['winner','名詞',1],
  ['wire','名詞',2],
  ['wise','形容詞',1],
  ['with','介系詞',1],
  ['woman','名詞',1],
  ['wood','名詞',1],
  ['wool','名詞',2],
  ['worker','名詞',1],
  ['worm','名詞',2],
  ['wrist','名詞',2],
  ['yard','名詞',2],
  ['yes','副詞',1],
  ['youth','名詞',1],
  ['yummy','形容詞',2],
];

// ── 工具函式 ──────────────────────────────────────────────────────

function loadCache() {
  if (RESET && fs.existsSync(CACHE_FILE)) fs.unlinkSync(CACHE_FILE);
  if (!fs.existsSync(CACHE_FILE)) return {};
  try { return JSON.parse(fs.readFileSync(CACHE_FILE, 'utf-8')); }
  catch { return {}; }
}

function saveCache(cache) {
  fs.writeFileSync(CACHE_FILE, JSON.stringify(cache, null, 2));
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

function getTag(level) {
  if (level === 1) return ['cap_2000', '基礎'];
  return ['cap_2000', '進階'];
}

async function generateBatch(model, words) {
  const list = words.map(w => `${w.word} (${w.pos})`).join(', ');
  const prompt = `你是台灣國中英語教材設計師。請為以下英文單字生成學習資料。

規格：
- phonetic：正確 IPA 音標
- definition：繁體中文定義，簡潔 10 字以內
- example_en：英文例句，CEFR B1 以下，10-15 字
- example_zh：例句繁體中文翻譯

單字（詞性）清單：${list}

只輸出 JSON 陣列，每個元素格式：
{"word":"...","phonetic":"...","definition":"...","example_en":"...","example_zh":"..."}`;

  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      if (attempt > 1) await sleep(3000 * attempt);
      const result = await model.generateContent(prompt);
      const raw = result.response.text();
      const json = raw.match(/\[[\s\S]*\]/)?.[0];
      if (!json) throw new Error('no JSON array found');
      return JSON.parse(json);
    } catch (err) {
      if (attempt === 3) throw err;
      console.warn(`  ↻ 重試 ${attempt}：${err.message}`);
    }
  }
}

// ── 主流程 ────────────────────────────────────────────────────────

async function main() {
  console.log('\n🚀 Vocatopia 單字匯入腳本');
  console.log(`   字庫清單：${WORD_LIST.length} 筆`);
  if (DRY_RUN) console.log('   ⚠ Dry-run 模式，不寫入資料庫\n');

  // 1. 讀取 DB 現有單字
  const { data: existing, error: fetchErr } = await supabase
    .from('words')
    .select('word');
  if (fetchErr) { console.error('✗ 無法讀取 DB：', fetchErr.message); process.exit(1); }

  const existingSet = new Set((existing || []).map(w => w.word));
  console.log(`   DB 已有：${existingSet.size} 筆`);

  // 2. 過濾出缺少的單字（去重）
  const seen = new Set();
  const missing = WORD_LIST.filter(([word]) => {
    if (existingSet.has(word) || seen.has(word)) return false;
    seen.add(word);
    return true;
  }).map(([word, pos, level], idx) => ({ word, pos, level, frequency_rank: idx + 1 }));

  console.log(`   待新增：${missing.length} 筆\n`);

  if (missing.length === 0) { console.log('✅ 資料庫已是最新，無需匯入！'); return; }
  if (DRY_RUN) { console.log('Dry-run 完畢，共需新增', missing.length, '筆'); return; }

  // 3. 載入 cache
  const cache = loadCache();
  const cachedCount = Object.keys(cache).length;
  if (cachedCount > 0) console.log(`   讀取快取：${cachedCount} 筆已生成\n`);

  // 4. Gemini 批次生成
  const model = genAI.getGenerativeModel({
    model: 'gemini-2.0-flash',   // 免費層配額較 2.5-flash 寬鬆
    generationConfig: { temperature: 0.4, maxOutputTokens: 8192 },
  });

  const toGenerate = missing.filter(w => !cache[w.word]);
  const batches = [];
  for (let i = 0; i < toGenerate.length; i += BATCH_SIZE) {
    batches.push(toGenerate.slice(i, i + BATCH_SIZE));
  }

  console.log(`📝 需生成：${toGenerate.length} 筆，共 ${batches.length} 批次\n`);

  for (let bi = 0; bi < batches.length; bi++) {
    const batch = batches[bi];
    process.stdout.write(`  批次 [${bi + 1}/${batches.length}] ${batch.map(w => w.word).slice(0, 5).join(' ')}... `);

    try {
      const results = await generateBatch(model, batch);
      for (const r of results) {
        if (r.word) cache[r.word] = r;
      }
      console.log(`✓ (${results.length} 筆)`);
    } catch (err) {
      console.log(`✗ 失敗：${err.message}`);
    }

    // 每 5 批存一次 cache
    if ((bi + 1) % 5 === 0) saveCache(cache);
    if (bi < batches.length - 1) await sleep(BATCH_DELAY_MS);
  }

  saveCache(cache);
  console.log('\n✅ 生成完畢\n');

  // 5. 準備 upsert 資料
  const rows = missing.map((w, idx) => {
    const gen = cache[w.word] || {};
    return {
      word:           w.word,
      pos:            w.pos,
      definition:     gen.definition || `(${w.word}) ${w.pos}`,
      phonetic:       gen.phonetic   || '',
      example_en:     gen.example_en || '',
      example_zh:     gen.example_zh || '',
      tags:           getTag(w.level),
      level:          w.level,
      frequency_rank: existingSet.size + idx + 1,
    };
  });

  // 6. 分批 insert（每批 100 筆）
  // 注意：已在步驟 2 過濾掉 DB 中已存在的字，所以用 insert 即可
  // 若仍遇到重複（WORD_LIST 內部重複），改為逐筆 insert 並跳過錯誤
  console.log(`💾 寫入資料庫，共 ${rows.length} 筆...`);
  let inserted = 0, failed = 0;

  for (let i = 0; i < rows.length; i += 100) {
    const chunk = rows.slice(i, i + 100);
    const { error } = await supabase
      .from('words')
      .insert(chunk);

    if (error) {
      // 批次失敗時改逐筆 insert，跳過個別衝突
      for (const row of chunk) {
        const { error: rowErr } = await supabase.from('words').insert(row);
        if (rowErr) { failed++; }
        else { inserted++; }
      }
    } else {
      inserted += chunk.length;
      process.stdout.write(`  ✓ ${inserted}/${rows.length}\r`);
    }
  }

  console.log(`\n\n🎉 匯入完成！成功 ${inserted} 筆，失敗 ${failed} 筆`);

  // 7. 驗證
  const { count } = await supabase
    .from('words')
    .select('*', { count: 'exact', head: true });
  console.log(`   資料庫目前共 ${count} 筆單字`);
}

main().catch(err => {
  console.error('\n❌ 錯誤：', err.message);
  process.exit(1);
});
