/** 人工撰寫批次 2：原創例句（cambridge-style-examples 規範：8-14 字、生活情境、繁中自然翻譯） */
const path = require('path');
const supabase = require(path.join(__dirname, '../server/db/supabase'));

const EX = {
  barn: ['The farmer keeps his cows in the big red barn.', '農夫把牛養在紅色的大穀倉裡。'],
  botany: ['She studies botany because she loves plants and flowers.', '她因為喜愛花草植物而研究植物學。'],
  brought: ['He brought his lunch to school in a blue bag.', '他用藍色袋子帶午餐到學校。'],
  'business hours': ['Our business hours are from nine in the morning to six.', '我們的營業時間是早上九點到六點。'],
  calcium: ['Milk gives your bones the calcium they need.', '牛奶提供骨骼所需的鈣質。'],
  camel: ['The camel carried heavy bags across the hot desert.', '駱駝背著沉重的行李穿越炎熱的沙漠。'],
  canyon: ['The river cut a deep canyon through the mountains.', '河流在山中切出一道深深的峽谷。'],
  caterpillar: ['The green caterpillar will become a butterfly one day.', '這隻綠色毛毛蟲有一天會變成蝴蝶。'],
  cavalry: ['In old wars, the cavalry rode horses into battle.', '在古代戰爭中，騎兵隊騎馬作戰。'],
  cellar: ['Grandpa keeps his old wine in the cool cellar.', '爺爺把陳年老酒存放在涼爽的地窖裡。'],
  cemetery: ['Every year we visit the cemetery to remember Grandma.', '我們每年都去墓園紀念奶奶。'],
  cenotaph: ['People placed flowers at the cenotaph on the holiday.', '假日時人們在紀念碑前獻花。'],
  centaur: ['The story is about a centaur, half man and half horse.', '這個故事講的是半人半馬的人馬。'],
  centigrade: ['Water boils at one hundred degrees centigrade.', '水在攝氏一百度時沸騰。'],
  centipede: ['A centipede with many legs crawled under the rock.', '一隻多腳的蜈蚣爬到石頭下面。'],
  chose: ['She chose the red dress for the party.', '她選了紅色洋裝去參加派對。'],
  cider: ['We drank warm apple cider on the cold night.', '在寒冷的夜晚我們喝了溫熱的蘋果酒。'],
  cistern: ['Rainwater is collected in a cistern on the roof.', '雨水收集在屋頂的蓄水池裡。'],
  citric: ['Lemons taste sour because of their citric acid.', '檸檬因為含檸檬酸而嚐起來酸酸的。'],
  citrus: ['Oranges and lemons are common citrus fruits.', '柳橙和檸檬是常見的柑橘類水果。'],
  civic: ['Voting is an important civic duty.', '投票是重要的公民義務。'],
  civil: ['Please keep the discussion civil and polite.', '請讓討論保持文明有禮。'],
  civilian: ['The soldier returned home and became a civilian again.', '那位軍人返鄉，重新成為平民。'],
  civility: ['She answered the rude question with calm civility.', '她以平靜有禮的態度回答那個無禮的問題。'],
  civilization: ["Ancient Egypt was one of the world's earliest civilizations.", '古埃及是世界上最早的文明之一。'],
  civilize: ['Schools help civilize young people through education.', '學校透過教育使年輕人更有教養。'],
  clad: ['The hikers were clad in warm jackets.', '登山客穿著保暖的外套。'],
  clairvoyance: ['He joked that only clairvoyance could predict the test questions.', '他開玩笑說只有千里眼才能預測考題。'],
  clam: ['We dug for clams on the beach at low tide.', '退潮時我們在海灘上挖蛤蜊。'],
  clamber: ['The children clambered over the big rocks by the sea.', '孩子們費力地爬過海邊的大石頭。'],
  clammy: ['His hands felt clammy before the big speech.', '大型演講前，他的手又濕又冷。'],
  clamor: ['The fans made a clamor for the singer to return.', '歌迷喧鬧著要歌手再次登台。'],
  clamp: ['Use a clamp to hold the two boards together.', '用夾子把兩塊木板固定在一起。'],
  clan: ['The whole clan gathers for dinner every New Year.', '整個家族每年過年都聚在一起吃飯。'],
  clandestine: ['The two friends held a clandestine meeting after school.', '兩個朋友放學後祕密見面。'],
  clang: ['The gate shut with a loud clang.', '大門砰的一聲關上，發出響亮的金屬聲。'],
  clank: ['We heard the clank of old machines in the factory.', '我們聽到工廠裡舊機器的鏗鏘聲。'],
  clarity: ['The teacher explained the rule with great clarity.', '老師非常清楚地解釋了規則。'],
  clash: ['The two teams clashed in the final game.', '兩隊在決賽中激烈交鋒。'],
  clasp: ["She clasped her mother's hand tightly in the crowd.", '在人群中她緊握著媽媽的手。'],
  classify: ['Scientists classify animals into different groups.', '科學家把動物分成不同的類別。'],
  claustrophobia: ['He takes the stairs because of his claustrophobia.', '因為幽閉恐懼症，他都走樓梯。'],
  clave: ['The musician tapped the clave to keep the rhythm.', '樂手敲擊擊木保持節奏。'],
  claw: ['The cat used its sharp claws to climb the tree.', '貓用尖銳的爪子爬樹。'],
  cleat: ['Soccer shoes have cleats to stop players from slipping.', '足球鞋有防滑釘，防止球員滑倒。'],
  cleavage: ['You can see the cleavage in the rock after the earthquake.', '地震後可以看到岩石上的裂縫。'],
  cleave: ['The chef cleaved the melon in two with one cut.', '廚師一刀把甜瓜劈成兩半。'],
  cleaver: ['The cook cut the meat with a heavy cleaver.', '廚師用沉重的菜刀切肉。'],
  clef: ['Music for the piano usually begins with a treble clef.', '鋼琴樂譜通常以高音譜號開頭。'],
  cleft: ['A small plant grew from the cleft in the rock.', '一株小植物從岩石的裂縫中長出來。'],
  clemency: ['The judge showed clemency to the young man.', '法官對那位年輕人從寬處理。'],
  clement: ['The weather was clement, perfect for a picnic.', '天氣溫和，非常適合野餐。'],
  clench: ['He clenched his fists when he heard the bad news.', '聽到壞消息時，他握緊了拳頭。'],
  clerestory: ['Sunlight entered the church through the clerestory windows.', '陽光透過教堂的高側窗照進來。'],
  clergy: ['The clergy led the prayers at the ceremony.', '神職人員在典禮上帶領禱告。'],
  cleric: ['The cleric spoke kindly to everyone after the service.', '儀式結束後，那位牧師親切地與大家交談。'],
  defend: ['The players worked together to defend their goal.', '球員們合力防守球門。'],
  destroy: ['The typhoon destroyed many houses near the coast.', '颱風摧毀了海岸附近的許多房屋。'],
  disease: ['Washing hands helps stop the spread of disease.', '洗手有助於阻止疾病傳播。'],
  document: ['Please sign this document and return it tomorrow.', '請在這份文件上簽名，明天交回。'],
  domestic: ['Domestic flights are usually cheaper than international ones.', '國內航班通常比國際航班便宜。'],
  dust: ['She wiped the dust off the old bookshelf.', '她擦掉舊書架上的灰塵。'],
  dying: ['The dying plant came back to life after some water.', '那株快枯死的植物澆水後活了過來。'],
  eager: ['The students were eager to start the summer vacation.', '學生們迫不及待想開始暑假。'],
  echo: ['Our voices made an echo in the empty hall.', '我們的聲音在空蕩的大廳裡迴盪。'],
  economics: ['My brother studies economics at the university.', '我哥哥在大學讀經濟學。'],
  economy: ['A good economy means more jobs for everyone.', '經濟好代表大家有更多工作機會。'],
  educate: ['Parents and teachers work together to educate children.', '父母和老師合力教育孩子。'],
  either: ['You can have either tea or coffee.', '你可以選茶或咖啡。'],
  eliminate: ['The team was eliminated in the first round.', '那支隊伍在第一輪就被淘汰了。'],
  emphasis: ['Our school puts emphasis on both study and sports.', '我們學校同時重視課業和運動。'],
  empire: ['The Roman Empire was very powerful long ago.', '羅馬帝國在很久以前非常強大。'],
  employee: ['Every employee gets a bonus at the end of the year.', '每位員工年底都會拿到獎金。'],
  employer: ['Her employer lets her work from home on Fridays.', '她的雇主讓她週五在家工作。'],
  employment: ['Many young people look for employment in big cities.', '許多年輕人到大城市找工作。'],
  enable: ['The new bridge enables people to cross the river quickly.', '新橋讓人們可以快速過河。'],
  endless: ['The desert seemed endless as we drove on.', '我們開車前進時，沙漠彷彿無邊無際。'],
  enforce: ['The police enforce traffic rules to keep roads safe.', '警察執行交通規則以維護道路安全。'],
  english: ['She practices English by watching movies.', '她藉著看電影練習英文。'],
  enormous: ['The whale is an enormous animal that lives in the sea.', '鯨魚是生活在海裡的巨大動物。'],
  enterprise: ['His small enterprise grew into a famous company.', '他的小事業成長為知名公司。'],
  enthusiasm: ['The new coach brought great enthusiasm to the team.', '新教練為球隊帶來極大的熱情。'],
  entry: ['The entry to the museum is free on Sundays.', '博物館週日免費入場。'],
  equality: ['The teacher treats every student with equality.', '老師平等對待每一位學生。'],
  equipment: ['The gym bought new equipment for the students.', '體育館為學生添購了新設備。'],
  era: ['We live in an era of fast technology.', '我們生活在科技快速發展的時代。'],
  escape: ['The bird escaped from its cage through the open window.', '那隻鳥從打開的窗戶逃出鳥籠。'],
  essay: ['I wrote an essay about my favorite season.', '我寫了一篇關於我最喜歡季節的文章。'],
  essence: ['The essence of friendship is trust.', '友誼的本質是信任。'],
  establish: ['The school was established more than fifty years ago.', '這所學校創立於五十多年前。'],
  establishment: ['That restaurant is the oldest establishment on the street.', '那家餐廳是這條街上最老的店家。'],
  estimate: ['We estimate the trip will take about three hours.', '我們估計這趟旅程大約需要三小時。'],
  eternal: ['The two friends promised eternal friendship.', '這兩位朋友承諾友誼永存。'],
  ethnic: ['Taiwan has many ethnic groups with different cultures.', '台灣有許多文化不同的族群。'],
  evaluate: ["The judges will evaluate each student's performance.", '評審會評估每位學生的表現。'],
  eventually: ['After many tries, she eventually passed the driving test.', '試了很多次之後，她終於通過駕照考試。'],
  everybody: ['Everybody in our class joined the cleaning activity.', '我們班每個人都參加了打掃活動。'],
  everyday: ['Brushing teeth is part of everyday life.', '刷牙是日常生活的一部分。'],
  everyone: ['Everyone cheered when the fireworks began.', '煙火開始時，所有人都歡呼起來。'],
  everything: ['She packed everything she needed for the trip.', '她收拾好旅行所需的一切。'],
  evidence: ['The police found evidence near the broken window.', '警方在破窗附近找到證據。'],
  exactly: ['The train left at exactly eight o\'clock.', '火車正好八點出發。'],
  examination: ['The final examination covers everything we learned this year.', '期末考涵蓋我們今年學的所有內容。'],
  exceed: ['Do not exceed the speed limit on this road.', '在這條路上不要超速。'],
  excellence: ['The school is known for its excellence in music.', '這所學校以音樂方面的卓越聞名。'],
  exception: ['Most stores open daily, but this one is an exception.', '大部分商店每天營業，但這家是例外。'],
  excess: ['Eating an excess of sugar is bad for your teeth.', '吃太多糖對牙齒不好。'],
  exchange: ['We exchanged gifts at the Christmas party.', '我們在聖誕派對上交換禮物。'],
  exclude: ["Don't exclude anyone from the game.", '玩遊戲時不要排擠任何人。'],
  exclusive: ['This club is exclusive to members only.', '這個俱樂部僅限會員使用。'],
  execute: ['The team executed the plan perfectly.', '團隊完美地執行了計畫。'],
  executive: ['The executive made an important decision for the company.', '那位主管為公司做了重要決定。'],
  exhaust: ['The long race exhausted all the runners.', '漫長的賽跑讓所有跑者筋疲力盡。'],
  exhibit: ['The museum will exhibit old paintings next month.', '博物館下個月將展出古老的畫作。'],
  exhibition: ['We saw a photo exhibition at the art center.', '我們在藝術中心看了攝影展。'],
  existence: ['Scientists question the existence of life on that planet.', '科學家質疑那顆行星上是否存在生命。'],
  expand: ['The small shop expanded into a large store.', '那家小店擴展成一家大商店。'],
  expansion: ["The city's rapid expansion surprised everyone.", '這座城市的快速擴張讓大家驚訝。'],
  expectation: ['The movie was far better than my expectation.', '這部電影遠超出我的期待。'],
  expense: ['They cut down on expenses by cooking at home.', '他們在家煮飯以減少開支。'],
  experiment: ['We did a fun science experiment in class today.', '今天我們在課堂上做了有趣的科學實驗。'],
  expert: ['She is an expert at fixing computers.', '她是修電腦的專家。'],
  explanation: ["The teacher's explanation made the math problem easy.", '老師的解說讓數學題變簡單了。'],
  explicit: ['The teacher gave explicit instructions for the homework.', '老師對作業給了明確的指示。'],
  explore: ['The children love to explore the forest behind their house.', '孩子們喜歡探索屋後的森林。'],
  export: ['Taiwan exports fruit to many countries.', '台灣外銷水果到許多國家。'],
  expression: ['You can tell she is happy from her expression.', '從她的表情可以看出她很開心。'],
  extend: ['The library extended its opening hours during exams.', '考試期間圖書館延長開放時間。'],
  extension: ['They built an extension to make the house bigger.', '他們加蓋使房子變大。'],
  extensive: ['The park covers an extensive area near the river.', '公園在河邊佔地廣大。'],
  extent: ['I agree with you to some extent.', '某種程度上我同意你的看法。'],
  external: ['The external walls of the house were painted white.', '房子的外牆漆成白色。'],
  extract: ['This juice is extracted from fresh oranges.', '這果汁是從新鮮柳橙榨取的。'],
  extreme: ['The desert has extreme heat during the day.', '沙漠白天極度炎熱。'],
  extremely: ['The test was extremely difficult for everyone.', '這次考試對大家來說都極其困難。'],
  facility: ['The new sports facility has a pool and a gym.', '新的運動設施有泳池和健身房。'],
  facing: ['Our classroom windows are facing the playground.', '我們教室的窗戶面向操場。'],
  factor: ['Weather is an important factor in planning a trip.', '天氣是規劃旅行的重要因素。'],
  faculty: ['Humans have the faculty of speech.', '人類擁有說話的能力。'],
  fade: ['The color of the curtain faded in the strong sun.', '窗簾的顏色在烈日下褪色了。'],
  fairly: ['The teacher treats all students fairly.', '老師公平對待所有學生。'],
  faith: ['Have faith in yourself and keep trying.', '對自己要有信心，繼續努力。'],
  fantasy: ['The novel is a fantasy about dragons and magic.', '這本小說是關於龍與魔法的奇幻故事。'],
  farming: ['Farming is hard work, especially in summer.', '務農很辛苦，尤其是在夏天。'],
  fascinating: ['The science museum is fascinating for children.', '科學博物館對孩子來說十分迷人。'],
  fate: ['They met by chance and believed it was fate.', '他們偶然相遇，相信這是命運。'],
  favorable: ['The weather is favorable for sailing today.', '今天的天氣很適合航行。'],
  favourite: ['Blue is my favourite colour.', '藍色是我最喜歡的顏色。'],
  feature: ["The phone's best feature is its camera.", '這支手機最棒的特色是相機。'],
  federal: ['The federal government makes laws for the whole country.', '聯邦政府為全國制定法律。'],
  fetch: ['The dog loves to fetch the ball in the park.', '那隻狗喜歡在公園裡撿球。'],
  fierce: ['The fierce dog barked at every stranger.', '那隻凶猛的狗對每個陌生人吠叫。'],
  fifth: ['My classroom is on the fifth floor.', '我的教室在五樓。'],
  fighter: ['The boxer is a strong fighter who never gives up.', '那位拳擊手是永不放棄的堅強鬥士。'],
  fighting: ['The teacher stopped the fighting between the two boys.', '老師制止了兩個男孩的打架。'],
  file: ['Please put these papers in the blue file.', '請把這些文件放進藍色資料夾。'],
  filter: ['This filter makes the water clean and safe to drink.', '這個濾水器讓水乾淨又安全可飲用。'],
  finance: ['She studies finance and wants to work in a bank.', '她讀財金，想去銀行工作。'],
  financial: ['The company is in good financial condition.', '這家公司財務狀況良好。'],
  finding: ["The study's main finding surprised the scientists.", '這項研究的主要發現讓科學家驚訝。'],
  firmly: ['He firmly believes that practice makes perfect.', '他堅信熟能生巧。'],
  fiscal: ['The government plans its fiscal budget every year.', '政府每年規劃財政預算。'],
  fitness: ['Daily exercise improves your fitness.', '每天運動能增進體能。'],
  fixed: ['The meeting has a fixed time every Monday morning.', '會議固定在每週一早上舉行。'],
  flame: ["The candle's flame danced in the wind.", '燭火在風中搖曳。'],
  flavor: ['Chocolate is the most popular ice cream flavor.', '巧克力是最受歡迎的冰淇淋口味。'],
  flesh: ['The flesh of this peach is sweet and juicy.', '這顆水蜜桃的果肉香甜多汁。'],
  flexibility: ['Stretching every day improves your flexibility.', '每天伸展能改善柔軟度。'],
  flexible: ['My work hours are flexible, so I can start late.', '我的工作時間有彈性，可以晚點開始。'],
  float: ['The paper boat floated slowly across the pond.', '紙船緩緩漂過池塘。'],
  flowing: ['The girl has long, flowing hair.', '那女孩有一頭飄逸的長髮。'],
  fluid: ['Drink plenty of fluids when you have a fever.', '發燒時要多補充水分。'],
  fold: ['Please fold the clothes and put them in the closet.', '請把衣服摺好放進衣櫃。'],
  following: ['Read the following sentences and answer the questions.', '閱讀以下句子並回答問題。'],
  forced: ['The rain forced us to cancel the picnic.', '大雨迫使我們取消野餐。'],
  forever: ['I will remember this wonderful day forever.', '我會永遠記得這美好的一天。'],
  formally: ['The principal formally welcomed the new teachers.', '校長正式歡迎新老師。'],
  formation: ['The birds flew south in a V formation.', '鳥群以 V 字隊形向南飛。'],
  formerly: ['This museum was formerly a train station.', '這座博物館以前是火車站。'],
  formula: ['The formula for water is H2O.', '水的化學式是 H2O。'],
  forth: ['The pendulum swung back and forth.', '鐘擺來回擺動。'],
  fortune: ['He made a fortune by selling computers.', '他靠賣電腦賺了一大筆錢。'],
  fossil: ['The children found a fish fossil in the rock.', '孩子們在岩石中發現魚的化石。'],
  foster: ["Reading fosters a child's imagination.", '閱讀能培養孩子的想像力。'],
  fought: ['The two teams fought hard for the championship.', '兩隊為冠軍奮力比拼。'],
  foul: ['The player got a foul for pushing.', '那位球員因推人被判犯規。'],
  foundation: ['Trust is the foundation of a good friendship.', '信任是良好友誼的基礎。'],
  founder: ['The founder of the school was a kind doctor.', '這所學校的創辦人是一位仁慈的醫生。'],
  fountain: ['Children played near the fountain in the square.', '孩子們在廣場的噴泉旁玩耍。'],
  fourth: ['Our team won fourth place in the relay race.', '我們隊在接力賽中得到第四名。'],
  fraction: ['A fraction of the students stayed after class.', '一小部分學生課後留下來。'],
  'opening hours': ['The opening hours of the library are posted on the door.', '圖書館的開放時間貼在門上。'],
  powered: ['This toy car is powered by two small batteries.', '這輛玩具車由兩顆小電池驅動。'],
  republic: ['A republic is a country without a king or queen.', '共和國是沒有國王或女王的國家。'],
  yell: ["Don't yell in the library; speak quietly.", '不要在圖書館大叫，請小聲說話。'],
  'dragon-boat': ['People race dragon-boats on the river every June.', '每年六月人們在河上比賽龍舟。'],
};

(async () => {
  let done = 0, miss = [];
  for (const [word, [example_en, example_zh]] of Object.entries(EX)) {
    const { data, error } = await supabase.from('words')
      .update({ example_en, example_zh }).eq('word', word).select('id');
    if (error) { console.error('FAIL', word, error.message); process.exit(1); }
    if (!data.length) { miss.push(word); continue; }
    if (++done % 50 === 0) console.log('進度', done);
  }
  console.log('批次2完成:', done, '| 找不到:', miss.join(',') || '無');
})();
