/** 人工撰寫批次 1：詞性 + 音標 + 英文定義（A2 改寫，原創措辭） */
const path = require('path');
const supabase = require(path.join(__dirname, '../server/db/supabase'));

const POS = {
  airlines: '名詞', attract: '動詞', auction: '名詞', barrel: '名詞', becoming: '形容詞', beware: '動詞',
  bid: '動詞', blast: '名詞', bleak: '形容詞', bleat: '動詞', bless: '動詞', blink: '動詞', bliss: '名詞',
  blister: '名詞', bloom: '動詞', bluff: '動詞', bog: '名詞', bonus: '名詞', bound: '動詞', brake: '名詞',
  breast: '名詞', brisk: '形容詞', broke: '形容詞', broken: '形容詞', broom: '名詞', brought: '動詞',
  browse: '動詞', bruise: '名詞', bubble: '名詞', buried: '形容詞', burning: '形容詞', bush: '名詞',
  cactus: '名詞', calculate: '動詞', camel: '名詞', canal: '名詞', candid: '形容詞', cane: '名詞',
  canine: '形容詞', cannon: '名詞', canoe: '名詞', canvas: '名詞', caravan: '名詞', carbohydrate: '名詞',
  carbon: '名詞', cardboard: '名詞', caretaker: '名詞', carnival: '名詞', carton: '名詞', carve: '動詞',
  casual: '形容詞', category: '名詞', caterpillar: '名詞', caucus: '名詞', caution: '名詞', cello: '名詞',
  cellular: '形容詞', celluloid: '名詞', celsius: '名詞', cement: '名詞', cenotaph: '名詞', censer: '名詞',
  censor: '動詞', censure: '動詞', census: '名詞', centaur: '名詞', centennial: '形容詞', centigrade: '名詞',
  ceremony: '名詞', certify: '動詞', cessation: '名詞', cession: '名詞', china: '名詞', chord: '名詞',
  chose: '動詞', chronic: '形容詞', cinnamon: '名詞', circular: '形容詞', circus: '名詞', citric: '形容詞',
  citrus: '名詞', civic: '形容詞', civility: '名詞', civilization: '名詞', clad: '形容詞', clam: '名詞',
  clammy: '形容詞', clandestine: '形容詞', clang: '名詞', clank: '名詞', classify: '動詞',
  claustrophobia: '名詞', clave: '名詞', cleat: '名詞', cleavage: '名詞', clemency: '名詞', clement: '形容詞',
  clergy: '名詞', 'dragon-boat': '名詞', powered: '形容詞', republic: '名詞', yell: '動詞',
};

const PHONETIC = {
  clave: '/ˈklɑː.veɪ/',
  clerestory: '/ˈklɪr.stɔːr.i/',
  'dragon-boat': '/ˈdræɡ.ən ˌboʊt/',
};

const DEF = {
  asylum: 'protection given by a country to people who escape danger',
  attract: 'to make someone or something come closer or feel interested',
  auction: 'a public sale where things go to the person who offers the most money',
  bar: 'a place that serves drinks, or a long piece of something hard',
  barrel: 'a large round container with flat ends',
  bias: 'an unfair feeling for or against someone or something',
  bid: 'to offer money for something, especially at a sale',
  blast: 'a sudden strong explosion or rush of air',
  bless: "to ask for God's care and protection for someone",
  blink: 'to close and open your eyes very quickly',
  blister: 'a small bubble of skin filled with liquid, caused by rubbing or burning',
  bluff: 'to pretend to be strong or sure in order to trick someone',
  bonus: 'extra money or a pleasant extra thing',
  bowls: 'deep, round dishes used for holding food or liquid',
  brake: 'the part of a vehicle that makes it slow down or stop',
  broom: 'a brush with a long handle used for cleaning floors',
  browse: 'to look through things slowly without searching for anything special',
  bruise: 'a dark mark on your skin made when you fall or get hit',
  bubble: 'a small ball of air inside a liquid',
  budget: 'a plan that shows how much money you can spend',
  burger: 'a round, flat piece of meat served in bread',
  bush: 'a plant like a small, low tree',
  camel: 'a large desert animal with one or two raised parts on its back',
  canal: 'a man-made river for boats or for carrying water',
  cannon: 'a large, heavy gun used in the past',
  canoe: 'a small, light, narrow boat that you move with a paddle',
  caravan: 'a vehicle that people can live and travel in',
  carbohydrate: 'a substance in foods like rice and bread that gives you energy',
  career: 'a job or profession that you do for a long time',
  caretaker: 'a person whose job is to look after a building',
  carton: 'a box made of thick paper for holding food or drink',
  carve: 'to cut wood or stone into a shape',
  category: 'a group of things that are similar in some way',
  caterpillar: 'a small, long animal that turns into a butterfly',
  caucus: 'a meeting of members of a political group',
  cello: 'a large musical instrument with strings that you play sitting down',
  celsius: 'a way of measuring temperature in which water freezes at zero degrees',
  cement: 'a gray powder mixed with water that becomes hard, used in building',
  cenotaph: 'a public monument built to remember people who died in war',
  censer: 'a container in which incense is burned during ceremonies',
  censor: 'to remove parts of books or films that are not allowed',
  census: 'an official count of all the people living in a country',
  centaur: 'a creature in old stories that is half human and half horse',
  certification: 'an official paper that proves something is true or done',
  certify: 'to state officially that something is true or correct',
  cession: 'the act of giving land or rights to another country',
  challenge: 'something difficult that tests your ability',
  china: 'cups, plates, and bowls made of fine white clay',
  cinnamon: 'a sweet-smelling brown spice used in cooking',
  circus: 'a show with clowns and animals in a big tent',
  citizen: 'a person who belongs to a country',
  citrus: 'fruit like oranges and lemons',
  civilization: 'a society with a high level of culture and order',
  clam: 'a sea animal with a shell in two parts',
  clang: 'a loud ringing sound of metal hitting something',
  clank: 'a short, loud sound of heavy metal pieces hitting each other',
  classify: 'to put things into groups by type',
  clave: 'a wooden stick used to make rhythm in music',
  cleat: 'a small piece on the bottom of a shoe that stops you from slipping',
  cleavage: 'a split or space between two things',
  community: 'all the people who live in one area',
  conditioning: 'a system that cools the air in a room',
  conservation: 'the protection of nature',
  container: 'an object like a box used for keeping things inside',
  contribution: 'something you give to help a person or group',
  developing: 'growing or changing into something better',
  digital: 'using computer technology or numbers',
  digitally: 'by using computer technology',
  disadvantages: 'things that make something less good',
  dislocated: 'describing a bone that has moved out of its place',
  districts: 'areas of a city or country',
  draft: 'an early version of a piece of writing',
  dust: 'very small pieces of dry dirt in the air or on things',
  empathy: 'the ability to understand how another person feels',
  escape: 'to get away from a place or a dangerous situation',
  essay: 'a short piece of writing about a subject',
  ethnic: 'relating to a group of people with the same culture',
  europe: 'the continent that includes countries such as France and Germany',
  exception: 'someone or something that a rule does not include',
  certainly: 'without any doubt',
  figure: 'a number, or the shape of a person',
  'fly away': 'to leave a place by flying',
  hairdresser: 'a person whose job is to cut and style hair',
  lift: 'a machine that carries people up and down in a building, or to pick something up',
  liter: 'a unit for measuring liquid',
  mashed: 'pressed until soft and smooth',
  mostly: 'mainly, or most of the time',
  nation: 'a country and its people',
  nest: 'a home that birds make for their eggs',
  note: 'a short written message',
  path: 'a narrow way that people walk along',
  pile: 'a number of things placed on top of each other',
  possessive: 'wanting to keep someone or something only for yourself',
  puppy: 'a young dog',
  purely: 'only, or completely',
  rare: 'not often seen or found',
  rob: 'to take money or things from a person or place illegally',
  scared: 'feeling afraid',
  schoolday: 'a day on which students go to school',
  ski: 'to move over snow on long, flat boards',
  social: 'relating to people and the way they live together',
  soul: 'the spirit part of a person that some believe lives forever',
  stove: 'a piece of kitchen equipment used for cooking',
  swan: 'a large white bird with a long neck that lives on water',
  throughout: 'in every part, or during the whole time',
  till: 'until, or a machine that holds money in a shop',
  title: 'the name of a book or film, or a word used before a name',
  turkey: 'a large bird kept for its meat',
  wallet: 'a small, flat case for money and cards',
  war: 'fighting between countries or groups',
  yell: 'to shout something very loudly',
};

(async () => {
  const words = new Set([...Object.keys(POS), ...Object.keys(PHONETIC), ...Object.keys(DEF)]);
  let done = 0, miss = [];
  for (const word of words) {
    const patch = {};
    if (POS[word]) patch.pos = POS[word];
    if (PHONETIC[word]) patch.phonetic = PHONETIC[word];
    if (DEF[word]) patch.definition = DEF[word];
    const { data, error } = await supabase.from('words').update(patch).eq('word', word).select('id');
    if (error) { console.error('FAIL', word, error.message); process.exit(1); }
    if (!data.length) { miss.push(word); continue; }
    done++;
  }
  console.log('批次1完成:', done, '| 找不到:', miss.join(',') || '無');
})();
